-- Complete server-only item banks and reproducible balanced random delivery.
--
-- This migration replaces the unexecuted fixed v1.1 form registration. It does
-- not mutate historical attempts, results, payments, group memberships or IDs.
-- Every delivered form is recorded as a private session snapshot before answers
-- are accepted, so a result can be audited even after the active bank changes.

create table if not exists public.ai_assessment_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  assessment_kind text not null check (assessment_kind in ('capability', 'personality')),
  instrument_id text not null references public.ai_assessment_instruments(id),
  item_bank_version text not null,
  presentation jsonb not null,
  status text not null default 'open' check (status in ('open', 'completed', 'expired')),
  expires_at timestamptz not null,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ai_assessment_sessions_user_kind_created_idx
  on public.ai_assessment_sessions (user_id, assessment_kind, created_at desc);

alter table public.ai_assessment_attempts
  add column if not exists assessment_session_id uuid
    references public.ai_assessment_sessions(id) on delete restrict;

create unique index if not exists ai_assessment_attempts_one_per_session_idx
  on public.ai_assessment_attempts (assessment_session_id)
  where assessment_session_id is not null;

create table if not exists public.ai_style_items (
  id text primary key check (id ~ '^(ES|CO|RA|PD|FX)[0-9]{2}$'),
  item_bank_version text not null,
  axis_code text not null check (axis_code in ('ES', 'CO', 'RA', 'PD')),
  item_type text not null check (item_type in ('likert', 'forced_choice')),
  prompt_payload jsonb not null,
  scoring_payload jsonb not null,
  status text not null default 'candidate' check (status in ('candidate', 'pilot', 'active', 'retired')),
  exposure_count bigint not null default 0 check (exposure_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ai_style_items_bank_axis_idx
  on public.ai_style_items (item_bank_version, axis_code, item_type)
  where status = 'active';

insert into public.ai_assessment_instruments (
  id, framework_version, item_bank_version, scoring_version,
  instrument_type, title, description, item_count, status, config
)
values
  (
    'pacf-quick-v1.1-random',
    'pacf-1.0.0',
    'pacf-item-bank-1.1.0',
    'pacf-scoring-1.1.0',
    'quick',
    '个人 AI 能力随机筛查 v1.1',
    '从 120 道服务端题库按六维均衡抽取 42 道题；每个维度覆盖全部核心能力点，用于稳定定位学习起点。',
    42,
    'candidate',
    '{"sampling":{"dimensions":["M","F","T","V","C","S"],"items_per_dimension":7,"coverage":"all five competencies per dimension","eligible_item_types":["objective","scenario"]},"pool_size":120,"evidence_grade":"screening"}'::jsonb
  ),
  (
    'ai-usage-style-v1.1-random-beta',
    'ai-usage-style-v1',
    'ai-style-item-bank-1.1.0',
    'ai-style-scoring-1.1.0',
    'personality',
    'AI 使用风格随机画像 Beta',
    '从 56 道计分陈述中按四条偏好轴均衡抽取 32 道，并附 4 道不计分行为权衡题；风格不代表能力高低。',
    36,
    'candidate',
    '{"sampling":{"axes":["ES","CO","RA","PD"],"scored_items_per_axis":8,"per_pole":4,"experimental_item_count":4},"scored_pool_size":56,"construct":"usage_style_not_capability","public_label":"beta"}'::jsonb
  )
on conflict (id) do update
set
  framework_version = excluded.framework_version,
  item_bank_version = excluded.item_bank_version,
  scoring_version = excluded.scoring_version,
  title = excluded.title,
  description = excluded.description,
  item_count = excluded.item_count,
  config = excluded.config,
  updated_at = now();

insert into public.ai_assessment_items (
  id, item_bank_version, competency_id, dimension_code, target_level,
  item_type, prompt_payload, scoring_payload, rationale, source_anchors,
  quick_eligible, status
)
values
($$PACF-M01-O1$$, 'pacf-item-bank-1.1.0', $$M01$$, $$M$$, 1, $$objective$$, $${"stem":"下面哪一项最准确地描述了“大语言模型”和“聊天产品”的关系？","options":[{"id":"A","text":"二者完全相同，只是叫法不同"},{"id":"B","text":"聊天产品通常把模型、界面、账户、工具和安全策略组合在一起"},{"id":"C","text":"大语言模型是聊天产品中的长期记忆数据库"},{"id":"D","text":"聊天产品一定只使用一个固定模型"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":3},{"id":"C","score":0},{"id":"D","score":0}]}$$::jsonb, $$产品通常是模型及其外围能力的封装，不能把产品名直接等同于模型。$$, array[$$S17$$, $$S18$$, $$P03$$]::text[], true, 'active'),
($$PACF-M01-S1$$, 'pacf-item-bank-1.1.0', $$M01$$, $$M$$, 2, $$scenario$$, $${"stem":"团队说要“做一个 Agent 自动整理客户反馈”。你首先应该做什么？","options":[{"id":"A","text":"直接选择一个多 Agent 平台"},{"id":"B","text":"先写一个人格提示词让它扮演客服"},{"id":"C","text":"先确认任务是否只需固定步骤的 Workflow"},{"id":"D","text":"画出模型、数据、工具、状态、权限和人工接管，再选择最小架构"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":1},{"id":"C","score":2},{"id":"D","score":3}]}$$::jsonb, $$高级表现是先理解构件和任务，再决定是否需要 Agent。$$, array[$$S17$$, $$S18$$, $$P01$$, $$P10$$]::text[], true, 'active'),
($$PACF-M01-C1$$, 'pacf-item-bank-1.1.0', $$M01$$, $$M$$, 3, $$constructed$$, $${"stem":"用不超过 180 字，向完全不懂技术的人解释：模型、AI 产品、工具调用、工作流和 Agent 有什么不同。","rubric":[{"id":"M01-1","description":"五个概念均有清楚定义","maxPoints":1},{"id":"M01-2","description":"指出构件之间的组合关系","maxPoints":1},{"id":"M01-3","description":"至少给出一个同任务对比例子","maxPoints":1},{"id":"M01-4","description":"没有把 Agent 等同于聊天机器人或自动化脚本","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"M01-1","description":"五个概念均有清楚定义","maxPoints":1},{"id":"M01-2","description":"指出构件之间的组合关系","maxPoints":1},{"id":"M01-3","description":"至少给出一个同任务对比例子","maxPoints":1},{"id":"M01-4","description":"没有把 Agent 等同于聊天机器人或自动化脚本","maxPoints":1}]}$$::jsonb, $$检验是否形成可迁移的系统构件心智模型。$$, array[$$S17$$, $$S18$$, $$P01$$]::text[], false, 'active'),
($$PACF-M01-P1$$, 'pacf-item-bank-1.1.0', $$M01$$, $$M$$, 4, $$practical$$, $${"stem":"为“每周收集用户反馈并生成待办”画出三种方案：人工+聊天、固定 Workflow、Agent。标出模型、工具、数据、状态和人工节点。","rubric":[{"id":"M01-1","description":"三种方案的构件标注完整","maxPoints":1},{"id":"M01-2","description":"能说明固定路径与动态决策差别","maxPoints":1},{"id":"M01-3","description":"给出各自适用条件","maxPoints":1},{"id":"M01-4","description":"最终选择有成本与风险依据","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"M01-1","description":"三种方案的构件标注完整","maxPoints":1},{"id":"M01-2","description":"能说明固定路径与动态决策差别","maxPoints":1},{"id":"M01-3","description":"给出各自适用条件","maxPoints":1},{"id":"M01-4","description":"最终选择有成本与风险依据","maxPoints":1}]}$$::jsonb, $$要求把术语转化为真实架构判断。$$, array[$$S17$$, $$S18$$, $$S20$$]::text[], false, 'active'),
($$PACF-M02-O1$$, 'pacf-item-bank-1.1.0', $$M02$$, $$M$$, 1, $$objective$$, $${"stem":"为什么模型给出的论文标题和链接看起来很真实，仍然需要核验？","options":[{"id":"A","text":"链接只在手机上才会失效"},{"id":"B","text":"只有免费模型才会编造"},{"id":"C","text":"只要要求“不要编造”就不需要核验"},{"id":"D","text":"模型可能按语言模式生成并不存在的细节"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":0},{"id":"C","score":0},{"id":"D","score":3}]}$$::jsonb, $$生成式模型以概率方式生成内容，流畅度不等于事实真实性。$$, array[$$S15$$, $$P04$$, $$P05$$]::text[], true, 'active'),
($$PACF-M02-S1$$, 'pacf-item-bank-1.1.0', $$M02$$, $$M$$, 2, $$scenario$$, $${"stem":"AI 对同一道业务题前后给出两个不同数字，你最合适的处理方式是？","options":[{"id":"A","text":"多问几遍，用出现次数最多的答案"},{"id":"B","text":"把温度调低后直接采用"},{"id":"C","text":"检查数据来源、计算过程和口径，必要时用确定性工具复算"},{"id":"D","text":"选语气更肯定的一个"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":1},{"id":"B","score":2},{"id":"C","score":3},{"id":"D","score":0}]}$$::jsonb, $$波动提示需要证据与确定性验证，不能用多数投票替代事实。$$, array[$$S12$$, $$S14$$, $$P05$$]::text[], true, 'active'),
($$PACF-M02-C1$$, 'pacf-item-bank-1.1.0', $$M02$$, $$M$$, 3, $$constructed$$, $${"stem":"解释“提示词可以降低部分错误概率，但不能保证没有幻觉”，并给出两个不同风险等级的例子。","rubric":[{"id":"M02-1","description":"解释概率生成或知识边界","maxPoints":1},{"id":"M02-2","description":"区分低风险和高风险任务","maxPoints":1},{"id":"M02-3","description":"给出提示之外的核验措施","maxPoints":1},{"id":"M02-4","description":"说明何时应拒用或转向专业人士","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"M02-1","description":"解释概率生成或知识边界","maxPoints":1},{"id":"M02-2","description":"区分低风险和高风险任务","maxPoints":1},{"id":"M02-3","description":"给出提示之外的核验措施","maxPoints":1},{"id":"M02-4","description":"说明何时应拒用或转向专业人士","maxPoints":1}]}$$::jsonb, $$防止把可靠性简化为提示词技巧。$$, array[$$S14$$, $$S15$$, $$P04$$]::text[], false, 'active'),
($$PACF-M02-P1$$, 'pacf-item-bank-1.1.0', $$M02$$, $$M$$, 4, $$practical$$, $${"stem":"用同一事实型问题分别测试两种模型三次，记录差异，并设计一套不依赖“多问几遍”的核验流程。","rubric":[{"id":"M02-1","description":"完整记录六次输出差异","maxPoints":1},{"id":"M02-2","description":"定位关键可核验主张","maxPoints":1},{"id":"M02-3","description":"使用原始来源或确定性工具","maxPoints":1},{"id":"M02-4","description":"总结模型适用边界而非只评输赢","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"M02-1","description":"完整记录六次输出差异","maxPoints":1},{"id":"M02-2","description":"定位关键可核验主张","maxPoints":1},{"id":"M02-3","description":"使用原始来源或确定性工具","maxPoints":1},{"id":"M02-4","description":"总结模型适用边界而非只评输赢","maxPoints":1}]}$$::jsonb, $$通过实验理解不确定性与核验。$$, array[$$S12$$, $$S14$$]::text[], false, 'active'),
($$PACF-M03-O1$$, 'pacf-item-bank-1.1.0', $$M03$$, $$M$$, 1, $$objective$$, $${"stem":"下面哪项最准确地区分“当前上下文”和“长期记忆”？","options":[{"id":"A","text":"二者都等于模型训练数据"},{"id":"B","text":"只要上传文件，模型就永久记住全文"},{"id":"C","text":"上下文是当前任务可用的信息，长期记忆是跨会话保存并可再次取用的信息"},{"id":"D","text":"上下文永久保存，长期记忆只在一次回答中有效"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":0},{"id":"C","score":3},{"id":"D","score":0}]}$$::jsonb, $$上下文、长期记忆、训练知识和文件检索是不同机制。$$, array[$$M03$$, $$P06$$]::text[], true, 'active'),
($$PACF-M03-S1$$, 'pacf-item-bank-1.1.0', $$M03$$, $$M$$, 2, $$scenario$$, $${"stem":"一个长对话已经混入多版需求，AI 开始反复遗漏。最佳下一步是？","options":[{"id":"A","text":"让 AI 猜测哪一版有效"},{"id":"B","text":"整理当前目标、已确认决定、材料版本和待办，开启干净会话继续"},{"id":"C","text":"继续补一句“请认真阅读上文”"},{"id":"D","text":"重复发送最近一条要求"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":2},{"id":"B","score":3},{"id":"C","score":0},{"id":"D","score":1}]}$$::jsonb, $$状态摘要和干净交接比无限追加上下文更可靠。$$, array[$$P06$$, $$F04$$]::text[], true, 'active'),
($$PACF-M03-C1$$, 'pacf-item-bank-1.1.0', $$M03$$, $$M$$, 3, $$constructed$$, $${"stem":"比较模型训练知识、联网搜索、RAG、会话上下文和长期记忆。分别说明它们可能过时或出错的地方。","rubric":[{"id":"M03-1","description":"五类信息来源均被区分","maxPoints":1},{"id":"M03-2","description":"指出时效性差异","maxPoints":1},{"id":"M03-3","description":"指出检索与生成仍可能出错","maxPoints":1},{"id":"M03-4","description":"说明用户如何确认当前依据","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"M03-1","description":"五类信息来源均被区分","maxPoints":1},{"id":"M03-2","description":"指出时效性差异","maxPoints":1},{"id":"M03-3","description":"指出检索与生成仍可能出错","maxPoints":1},{"id":"M03-4","description":"说明用户如何确认当前依据","maxPoints":1}]}$$::jsonb, $$检验知识边界与状态意识。$$, array[$$S06$$, $$M03$$]::text[], false, 'active'),
($$PACF-M03-P1$$, 'pacf-item-bank-1.1.0', $$M03$$, $$M$$, 4, $$practical$$, $${"stem":"把一个至少三阶段的长任务拆成可跨会话恢复的状态包，并让另一会话仅凭状态包继续执行。","rubric":[{"id":"M03-1","description":"状态包含目标、材料、决定与待办","maxPoints":1},{"id":"M03-2","description":"清楚标注版本和未决问题","maxPoints":1},{"id":"M03-3","description":"新会话能正确恢复","maxPoints":1},{"id":"M03-4","description":"记录并修复一次上下文丢失","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"M03-1","description":"状态包含目标、材料、决定与待办","maxPoints":1},{"id":"M03-2","description":"清楚标注版本和未决问题","maxPoints":1},{"id":"M03-3","description":"新会话能正确恢复","maxPoints":1},{"id":"M03-4","description":"记录并修复一次上下文丢失","maxPoints":1}]}$$::jsonb, $$以恢复能力证明上下文管理，而非依赖产品记忆。$$, array[$$P06$$, $$CORE-11$$]::text[], false, 'active'),
($$PACF-M04-O1$$, 'pacf-item-bank-1.1.0', $$M04$$, $$M$$, 2, $$objective$$, $${"stem":"选择 AI 工具时，下面哪组因素最完整？","options":[{"id":"A","text":"朋友使用数量和广告折扣"},{"id":"B","text":"是否热门、界面是否漂亮"},{"id":"C","text":"模型排行榜和参数量"},{"id":"D","text":"质量、时效、隐私、成本、工具能力和集成条件"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":0},{"id":"C","score":0},{"id":"D","score":3}]}$$::jsonb, $$工具选择必须与任务和约束匹配。$$, array[$$S20$$, $$P09$$]::text[], true, 'active'),
($$PACF-M04-S1$$, 'pacf-item-bank-1.1.0', $$M04$$, $$M$$, 3, $$scenario$$, $${"stem":"每月只处理 20 份格式固定的表格，人工核对很快。有人建议搭多 Agent 系统。最佳决策是？","options":[{"id":"A","text":"只要能节省一分钟就全自动化"},{"id":"B","text":"因为 Agent 更先进，立即搭建"},{"id":"C","text":"先购买最贵模型保证效果"},{"id":"D","text":"先比较模板/脚本/单次模型方案的成本和错误率"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":3},{"id":"B","score":0},{"id":"C","score":1},{"id":"D","score":2}]}$$::jsonb, $$低频固定任务可能用简单方案更可靠。$$, array[$$S18$$, $$S20$$, $$P15$$]::text[], true, 'active'),
($$PACF-M04-C1$$, 'pacf-item-bank-1.1.0', $$M04$$, $$M$$, 3, $$constructed$$, $${"stem":"为“公开资料行业简报”和“含客户隐私的内部分析”分别提出工具选择，并说明质量、隐私、成本和可追溯性权衡。","rubric":[{"id":"M04-1","description":"两个场景选择不同且合理","maxPoints":1},{"id":"M04-2","description":"覆盖质量和时效","maxPoints":1},{"id":"M04-3","description":"覆盖隐私与权限","maxPoints":1},{"id":"M04-4","description":"覆盖成本和证据追溯","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"M04-1","description":"两个场景选择不同且合理","maxPoints":1},{"id":"M04-2","description":"覆盖质量和时效","maxPoints":1},{"id":"M04-3","description":"覆盖隐私与权限","maxPoints":1},{"id":"M04-4","description":"覆盖成本和证据追溯","maxPoints":1}]}$$::jsonb, $$观察能否按场景做多目标权衡。$$, array[$$S07$$, $$S20$$]::text[], false, 'active'),
($$PACF-M04-P1$$, 'pacf-item-bank-1.1.0', $$M04$$, $$M$$, 4, $$practical$$, $${"stem":"选择一个真实任务，对比人工、单次模型、固定 Workflow 和 Agent 四种方案，形成带测量数据的选型报告。","rubric":[{"id":"M04-1","description":"建立统一质量基线","maxPoints":1},{"id":"M04-2","description":"测量时间与成本","maxPoints":1},{"id":"M04-3","description":"识别风险和失控半径","maxPoints":1},{"id":"M04-4","description":"选择最小可靠方案并说明放弃项","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"M04-1","description":"建立统一质量基线","maxPoints":1},{"id":"M04-2","description":"测量时间与成本","maxPoints":1},{"id":"M04-3","description":"识别风险和失控半径","maxPoints":1},{"id":"M04-4","description":"选择最小可靠方案并说明放弃项","maxPoints":1}]}$$::jsonb, $$高阶选型必须有实测而不是趋势判断。$$, array[$$S18$$, $$S20$$]::text[], false, 'active'),
($$PACF-M05-O1$$, 'pacf-item-bank-1.1.0', $$M05$$, $$M$$, 1, $$objective$$, $${"stem":"AI 生成的内容造成业务错误时，下面哪项最准确？","options":[{"id":"A","text":"模型承担全部责任"},{"id":"B","text":"只要披露用了 AI，人就没有责任"},{"id":"C","text":"最终采用和发布的人或组织仍需承担相应责任"},{"id":"D","text":"使用付费模型即可转移责任"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":0},{"id":"C","score":3},{"id":"D","score":0}]}$$::jsonb, $$AI 辅助不会自动转移人的判断和责任。$$, array[$$S20$$, $$S22$$]::text[], true, 'active'),
($$PACF-M05-S1$$, 'pacf-item-bank-1.1.0', $$M05$$, $$M$$, 2, $$scenario$$, $${"stem":"AI 给出涉及健康、法律或财务的重要建议，用户应如何使用？","options":[{"id":"A","text":"直接照做，因为模型读过很多资料"},{"id":"B","text":"让同一个模型再确认一次"},{"id":"C","text":"只看网友是否也这样做"},{"id":"D","text":"把 AI 用于整理问题和资料，再查权威来源并向合格专业人士确认"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":1},{"id":"C","score":2},{"id":"D","score":3}]}$$::jsonb, $$高风险判断必须保留合格人工责任。$$, array[$$S07$$, $$S20$$]::text[], true, 'active'),
($$PACF-M05-C1$$, 'pacf-item-bank-1.1.0', $$M05$$, $$M$$, 3, $$constructed$$, $${"stem":"为“用 AI 初筛求职简历”划分 AI 可做、人必须做、需要升级审批的工作，并说明理由。","rubric":[{"id":"M05-1","description":"识别偏差与公平风险","maxPoints":1},{"id":"M05-2","description":"明确 AI 可辅助的低风险步骤","maxPoints":1},{"id":"M05-3","description":"保留关键人类判断","maxPoints":1},{"id":"M05-4","description":"定义责任人和申诉/升级路径","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"M05-1","description":"识别偏差与公平风险","maxPoints":1},{"id":"M05-2","description":"明确 AI 可辅助的低风险步骤","maxPoints":1},{"id":"M05-3","description":"保留关键人类判断","maxPoints":1},{"id":"M05-4","description":"定义责任人和申诉/升级路径","maxPoints":1}]}$$::jsonb, $$检验人机分工是否同时考虑价值与责任。$$, array[$$S05$$, $$S07$$]::text[], false, 'active'),
($$PACF-M05-P1$$, 'pacf-item-bank-1.1.0', $$M05$$, $$M$$, 5, $$practical$$, $${"stem":"选择一个团队 AI 用例，制作 RACI 或等价责任矩阵，并进行一次异常事件桌面推演。","rubric":[{"id":"M05-1","description":"职责与审批人明确","maxPoints":1},{"id":"M05-2","description":"AI 权限和禁止项明确","maxPoints":1},{"id":"M05-3","description":"异常升级与停止条件可执行","maxPoints":1},{"id":"M05-4","description":"推演后形成改进记录","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"M05-1","description":"职责与审批人明确","maxPoints":1},{"id":"M05-2","description":"AI 权限和禁止项明确","maxPoints":1},{"id":"M05-3","description":"异常升级与停止条件可执行","maxPoints":1},{"id":"M05-4","description":"推演后形成改进记录","maxPoints":1}]}$$::jsonb, $$组织级能力要能在事故中保持责任清晰。$$, array[$$S05$$, $$S07$$, $$ORG-02$$]::text[], false, 'active'),
($$PACF-F01-O1$$, 'pacf-item-bank-1.1.0', $$F01$$, $$F$$, 1, $$objective$$, $${"stem":"下面哪个请求最接近“定义了结果”，而不只是描述动作？","options":[{"id":"A","text":"帮我写一下"},{"id":"B","text":"把这份材料处理好"},{"id":"C","text":"为第一次了解产品的用户写一页说明，使其能独立完成注册，包含步骤和常见错误"},{"id":"D","text":"你是世界级文案大师，请认真思考"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":0},{"id":"C","score":3},{"id":"D","score":0}]}$$::jsonb, $$结果定义应包含受众、目的和可观察交付。$$, array[$$S16$$, $$P02$$]::text[], true, 'active'),
($$PACF-F01-S1$$, 'pacf-item-bank-1.1.0', $$F01$$, $$F$$, 2, $$scenario$$, $${"stem":"老板说“用 AI 提升一下运营效率”。第一步应做什么？","options":[{"id":"A","text":"立刻列 50 个 AI 工具"},{"id":"B","text":"购买企业版聊天产品"},{"id":"C","text":"让 AI 生成完整方案"},{"id":"D","text":"澄清目标指标、受影响流程、用户和当前基线"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":1},{"id":"C","score":2},{"id":"D","score":3}]}$$::jsonb, $$模糊愿望要先转成可测问题。$$, array[$$S16$$, $$SYS-01$$]::text[], true, 'active'),
($$PACF-F01-C1$$, 'pacf-item-bank-1.1.0', $$F01$$, $$F$$, 3, $$constructed$$, $${"stem":"把“帮我做一份 AI 课程”改写为一个可执行问题定义，包含目标用户、真实问题、交付物和成功指标。","rubric":[{"id":"F01-1","description":"目标用户具体","maxPoints":1},{"id":"F01-2","description":"问题和使用场景清楚","maxPoints":1},{"id":"F01-3","description":"交付物可观察","maxPoints":1},{"id":"F01-4","description":"成功指标可检查","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"F01-1","description":"目标用户具体","maxPoints":1},{"id":"F01-2","description":"问题和使用场景清楚","maxPoints":1},{"id":"F01-3","description":"交付物可观察","maxPoints":1},{"id":"F01-4","description":"成功指标可检查","maxPoints":1}]}$$::jsonb, $$检验能否从动作导向转为结果导向。$$, array[$$S16$$, $$F01$$]::text[], false, 'active'),
($$PACF-F01-P1$$, 'pacf-item-bank-1.1.0', $$F01$$, $$F$$, 4, $$practical$$, $${"stem":"访谈一位真实用户，把其模糊需求整理成问题陈述、非目标、约束和验收指标，并让用户确认。","rubric":[{"id":"F01-1","description":"使用真实用户证据","maxPoints":1},{"id":"F01-2","description":"区分问题与预设方案","maxPoints":1},{"id":"F01-3","description":"列出非目标和约束","maxPoints":1},{"id":"F01-4","description":"获得用户确认或记录分歧","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"F01-1","description":"使用真实用户证据","maxPoints":1},{"id":"F01-2","description":"区分问题与预设方案","maxPoints":1},{"id":"F01-3","description":"列出非目标和约束","maxPoints":1},{"id":"F01-4","description":"获得用户确认或记录分歧","maxPoints":1}]}$$::jsonb, $$以真实需求确认避免闭门提示。$$, array[$$PROD-01$$, $$SYS-01$$]::text[], false, 'active'),
($$PACF-F02-O1$$, 'pacf-item-bank-1.1.0', $$F02$$, $$F$$, 1, $$objective$$, $${"stem":"复杂任务拆解时，最有用的原则是什么？","options":[{"id":"A","text":"按可验证的中间产物和依赖关系拆分"},{"id":"B","text":"尽量让 AI 一次完成所有步骤"},{"id":"C","text":"每一步都换一个模型"},{"id":"D","text":"每一步字数相同"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":3},{"id":"B","score":0},{"id":"C","score":0},{"id":"D","score":0}]}$$::jsonb, $$拆解应产生可检查的中间成果和清晰依赖。$$, array[$$S16$$, $$F02$$]::text[], true, 'active'),
($$PACF-F02-S1$$, 'pacf-item-bank-1.1.0', $$F02$$, $$F$$, 2, $$scenario$$, $${"stem":"要做一份带数据和引用的市场报告，哪种分工最稳妥？","options":[{"id":"A","text":"先生成结论，再寻找支持结论的资料"},{"id":"B","text":"分成问题定义、资料检索、数据核对、分析、写作和独立审校"},{"id":"C","text":"让多个模型同时写，选最长的一份"},{"id":"D","text":"让 AI 一次生成整份报告并直接提交"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":1},{"id":"B","score":2},{"id":"C","score":3},{"id":"D","score":0}]}$$::jsonb, $$高质量复杂任务需要可验证的阶段和独立审校。$$, array[$$S12$$, $$F02$$]::text[], true, 'active'),
($$PACF-F02-C1$$, 'pacf-item-bank-1.1.0', $$F02$$, $$F$$, 3, $$constructed$$, $${"stem":"把“发布一期关于 Agent 的科普内容”拆成任务树，标出依赖、AI 角色、人类角色和检查点。","rubric":[{"id":"F02-1","description":"任务覆盖研究到发布","maxPoints":1},{"id":"F02-2","description":"依赖顺序合理","maxPoints":1},{"id":"F02-3","description":"人机角色有依据","maxPoints":1},{"id":"F02-4","description":"设置关键检查点","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"F02-1","description":"任务覆盖研究到发布","maxPoints":1},{"id":"F02-2","description":"依赖顺序合理","maxPoints":1},{"id":"F02-3","description":"人机角色有依据","maxPoints":1},{"id":"F02-4","description":"设置关键检查点","maxPoints":1}]}$$::jsonb, $$考察任务结构和委派，而非提示词长度。$$, array[$$P01$$, $$S16$$]::text[], false, 'active'),
($$PACF-F02-P1$$, 'pacf-item-bank-1.1.0', $$F02$$, $$F$$, 4, $$practical$$, $${"stem":"选一个至少五步的真实任务，分别用“一次性交付”和“分阶段委派”完成，对比返工和质量。","rubric":[{"id":"F02-1","description":"两种方案使用同一标准","maxPoints":1},{"id":"F02-2","description":"记录中间产物和返工","maxPoints":1},{"id":"F02-3","description":"说明哪些步骤保留给人","maxPoints":1},{"id":"F02-4","description":"基于结果改进拆解模板","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"F02-1","description":"两种方案使用同一标准","maxPoints":1},{"id":"F02-2","description":"记录中间产物和返工","maxPoints":1},{"id":"F02-3","description":"说明哪些步骤保留给人","maxPoints":1},{"id":"F02-4","description":"基于结果改进拆解模板","maxPoints":1}]}$$::jsonb, $$通过对照实验验证拆解价值。$$, array[$$CORE-06$$, $$CORE-14$$]::text[], false, 'active'),
($$PACF-F03-O1$$, 'pacf-item-bank-1.1.0', $$F03$$, $$F$$, 1, $$objective$$, $${"stem":"给 AI 提供上下文时，什么最重要？","options":[{"id":"A","text":"提供与目标和判断直接相关的材料、边界与样例"},{"id":"B","text":"把所有历史聊天完整粘贴"},{"id":"C","text":"信息越多越好"},{"id":"D","text":"只给角色设定"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":3},{"id":"B","score":0},{"id":"C","score":0},{"id":"D","score":0}]}$$::jsonb, $$上下文应相关、结构化并服务于任务。$$, array[$$S16$$, $$P06$$]::text[], true, 'active'),
($$PACF-F03-S1$$, 'pacf-item-bank-1.1.0', $$F03$$, $$F$$, 2, $$scenario$$, $${"stem":"AI 写出的品牌文案很通用。最有效的改进是？","options":[{"id":"A","text":"提供真实受众、品牌主张、已有素材、禁用表达和正反例"},{"id":"B","text":"连续点击重新生成"},{"id":"C","text":"要求它更高级、更有网感"},{"id":"D","text":"把语气调得更热情"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":2},{"id":"B","score":3},{"id":"C","score":0},{"id":"D","score":1}]}$$::jsonb, $$具体材料和边界比抽象形容词更能减少偏差。$$, array[$$S16$$, $$P09$$]::text[], true, 'active'),
($$PACF-F03-C1$$, 'pacf-item-bank-1.1.0', $$F03$$, $$F$$, 3, $$constructed$$, $${"stem":"为“根据访谈写用户洞察”设计一个上下文包：列出必须提供、可选提供和禁止提供的信息。","rubric":[{"id":"F03-1","description":"必须材料足以完成任务","maxPoints":1},{"id":"F03-2","description":"可选材料有清楚用途","maxPoints":1},{"id":"F03-3","description":"识别隐私和无关信息","maxPoints":1},{"id":"F03-4","description":"包含正例/反例或质量边界","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"F03-1","description":"必须材料足以完成任务","maxPoints":1},{"id":"F03-2","description":"可选材料有清楚用途","maxPoints":1},{"id":"F03-3","description":"识别隐私和无关信息","maxPoints":1},{"id":"F03-4","description":"包含正例/反例或质量边界","maxPoints":1}]}$$::jsonb, $$兼测相关性和数据最小化。$$, array[$$S16$$, $$V03$$]::text[], false, 'active'),
($$PACF-F03-P1$$, 'pacf-item-bank-1.1.0', $$F03$$, $$F$$, 4, $$practical$$, $${"stem":"将一份杂乱材料整理成结构化上下文包，并让两个不同模型完成同一任务，比较一致性。","rubric":[{"id":"F03-1","description":"材料有清楚层级和版本","maxPoints":1},{"id":"F03-2","description":"目标与约束单独标注","maxPoints":1},{"id":"F03-3","description":"使用同一验收标准比较","maxPoints":1},{"id":"F03-4","description":"根据结果删除噪声或补充缺口","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"F03-1","description":"材料有清楚层级和版本","maxPoints":1},{"id":"F03-2","description":"目标与约束单独标注","maxPoints":1},{"id":"F03-3","description":"使用同一验收标准比较","maxPoints":1},{"id":"F03-4","description":"根据结果删除噪声或补充缺口","maxPoints":1}]}$$::jsonb, $$用迁移实验验证上下文设计。$$, array[$$CORE-11$$, $$M03$$]::text[], false, 'active'),
($$PACF-F04-O1$$, 'pacf-item-bank-1.1.0', $$F04$$, $$F$$, 1, $$objective$$, $${"stem":"AI 首次回答偏离需求时，最好的反馈通常是什么？","options":[{"id":"A","text":"换一种角色称呼"},{"id":"B","text":"重发同一句话"},{"id":"C","text":"说“这不对，重写”"},{"id":"D","text":"指出具体偏差、补充缺失信息并重申验收标准"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":0},{"id":"C","score":0},{"id":"D","score":3}]}$$::jsonb, $$可诊断反馈应指出偏差和标准。$$, array[$$S16$$, $$F04$$]::text[], true, 'active'),
($$PACF-F04-S1$$, 'pacf-item-bank-1.1.0', $$F04$$, $$F$$, 3, $$scenario$$, $${"stem":"一个多轮任务中，新信息与早先约束冲突。应该怎样处理？","options":[{"id":"A","text":"明确指出冲突，请求确认优先级，并更新状态与决策记录"},{"id":"B","text":"默认采用最新信息，不留记录"},{"id":"C","text":"让 AI 自己决定哪个更重要"},{"id":"D","text":"把两者都保留，期待模型兼容"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":3},{"id":"B","score":0},{"id":"C","score":1},{"id":"D","score":2}]}$$::jsonb, $$冲突约束需要人工确认和版本化状态。$$, array[$$P06$$, $$CORE-11$$]::text[], true, 'active'),
($$PACF-F04-C1$$, 'pacf-item-bank-1.1.0', $$F04$$, $$F$$, 3, $$constructed$$, $${"stem":"给出一段“AI 写得不好”的结果，写一轮可执行反馈，并说明你诊断的是目标、材料、约束还是推理问题。","rubric":[{"id":"F04-1","description":"指出具体偏差","maxPoints":1},{"id":"F04-2","description":"反馈可执行","maxPoints":1},{"id":"F04-3","description":"关联原验收标准","maxPoints":1},{"id":"F04-4","description":"正确识别主要问题来源","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"F04-1","description":"指出具体偏差","maxPoints":1},{"id":"F04-2","description":"反馈可执行","maxPoints":1},{"id":"F04-3","description":"关联原验收标准","maxPoints":1},{"id":"F04-4","description":"正确识别主要问题来源","maxPoints":1}]}$$::jsonb, $$避免无诊断的反复生成。$$, array[$$S16$$, $$F04$$]::text[], false, 'active'),
($$PACF-F04-P1$$, 'pacf-item-bank-1.1.0', $$F04$$, $$F$$, 4, $$practical$$, $${"stem":"完成一次跨三轮的复杂任务，保存每轮假设、反馈、决定和当前状态，随后交给另一人/会话继续。","rubric":[{"id":"F04-1","description":"每轮变化可追踪","maxPoints":1},{"id":"F04-2","description":"冲突与决定被记录","maxPoints":1},{"id":"F04-3","description":"状态摘要足以交接","maxPoints":1},{"id":"F04-4","description":"最终结果符合原标准","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"F04-1","description":"每轮变化可追踪","maxPoints":1},{"id":"F04-2","description":"冲突与决定被记录","maxPoints":1},{"id":"F04-3","description":"状态摘要足以交接","maxPoints":1},{"id":"F04-4","description":"最终结果符合原标准","maxPoints":1}]}$$::jsonb, $$同时检验迭代质量与状态可恢复性。$$, array[$$CORE-11$$, $$P06$$]::text[], false, 'active'),
($$PACF-F05-O1$$, 'pacf-item-bank-1.1.0', $$F05$$, $$F$$, 1, $$objective$$, $${"stem":"为什么最好在看 AI 输出之前写验收标准？","options":[{"id":"A","text":"可以让输出字数更多"},{"id":"B","text":"减少被流畅表达影响判断，并让反馈可重复"},{"id":"C","text":"可以保证模型永不出错"},{"id":"D","text":"只为了方便打分"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":3},{"id":"C","score":0},{"id":"D","score":0}]}$$::jsonb, $$预先标准能减少事后合理化和流畅性偏差。$$, array[$$S12$$, $$P13$$]::text[], true, 'active'),
($$PACF-F05-S1$$, 'pacf-item-bank-1.1.0', $$F05$$, $$F$$, 2, $$scenario$$, $${"stem":"你要让 AI 写一份给投资人的一页项目说明，哪个验收标准最有效？","options":[{"id":"A","text":"看起来专业"},{"id":"B","text":"语言有感染力"},{"id":"C","text":"控制在一页并覆盖问题、方案、证据、商业模式和下一步，关键数字有来源"},{"id":"D","text":"尽量详细完整"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":1},{"id":"C","score":2},{"id":"D","score":3}]}$$::jsonb, $$验收标准必须具体、可检查且与受众目的相关。$$, array[$$F05$$, $$P13$$]::text[], true, 'active'),
($$PACF-F05-C1$$, 'pacf-item-bank-1.1.0', $$F05$$, $$F$$, 3, $$constructed$$, $${"stem":"为“AI 生成的行业简报”写一份不超过 8 项的验收清单，覆盖内容、来源、时效和交付格式。","rubric":[{"id":"F05-1","description":"包含事实与来源","maxPoints":1},{"id":"F05-2","description":"包含时效与适用范围","maxPoints":1},{"id":"F05-3","description":"包含受众和完整性","maxPoints":1},{"id":"F05-4","description":"每项可明确判定通过/不通过","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"F05-1","description":"包含事实与来源","maxPoints":1},{"id":"F05-2","description":"包含时效与适用范围","maxPoints":1},{"id":"F05-3","description":"包含受众和完整性","maxPoints":1},{"id":"F05-4","description":"每项可明确判定通过/不通过","maxPoints":1}]}$$::jsonb, $$把主观好坏转成可操作标准。$$, array[$$CORE-08$$, $$S12$$]::text[], false, 'active'),
($$PACF-F05-P1$$, 'pacf-item-bank-1.1.0', $$F05$$, $$F$$, 4, $$practical$$, $${"stem":"在生成之前建立 rubric，盲评两份不同来源的 AI 输出，记录评分差异并修订 rubric。","rubric":[{"id":"F05-1","description":"rubric 在输出前完成","maxPoints":1},{"id":"F05-2","description":"盲评过程可复现","maxPoints":1},{"id":"F05-3","description":"差异有证据解释","maxPoints":1},{"id":"F05-4","description":"根据歧义改进标准但不迎合某一输出","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"F05-1","description":"rubric 在输出前完成","maxPoints":1},{"id":"F05-2","description":"盲评过程可复现","maxPoints":1},{"id":"F05-3","description":"差异有证据解释","maxPoints":1},{"id":"F05-4","description":"根据歧义改进标准但不迎合某一输出","maxPoints":1}]}$$::jsonb, $$实测标准的区分力和一致性。$$, array[$$CORE-08$$, $$S10$$]::text[], false, 'active'),
($$PACF-T01-O1$$, 'pacf-item-bank-1.1.0', $$T01$$, $$T$$, 1, $$objective$$, $${"stem":"环境变量最常见的用途是什么？","options":[{"id":"A","text":"把密钥安全地从公开代码中分离"},{"id":"B","text":"让网页字体更大"},{"id":"C","text":"永久保存模型回答"},{"id":"D","text":"替代数据库备份"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":3},{"id":"B","score":0},{"id":"C","score":0},{"id":"D","score":0}]}$$::jsonb, $$环境变量是配置与敏感信息管理的基础概念。$$, array[$$BRG-01$$, $$P11$$]::text[], true, 'active'),
($$PACF-T01-S1$$, 'pacf-item-bank-1.1.0', $$T01$$, $$T$$, 1, $$scenario$$, $${"stem":"教程要求上传 CSV，但你手里是 Excel 文件。最合适的做法是？","options":[{"id":"A","text":"把扩展名直接改成 .csv"},{"id":"B","text":"截图后上传"},{"id":"C","text":"先确认工作表和编码，再导出 CSV 并检查内容"},{"id":"D","text":"把整个电脑文件夹上传"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":1},{"id":"C","score":2},{"id":"D","score":3}]}$$::jsonb, $$基本格式转换必须保留数据并检查结果。$$, array[$$BRG-00$$, $$P11$$]::text[], true, 'active'),
($$PACF-T01-C1$$, 'pacf-item-bank-1.1.0', $$T01$$, $$T$$, 2, $$constructed$$, $${"stem":"向小白解释文件路径、文件格式、账户权限和 API Key，各给一个常见错误。","rubric":[{"id":"T01-1","description":"四个概念均准确","maxPoints":1},{"id":"T01-2","description":"错误例子真实","maxPoints":1},{"id":"T01-3","description":"说明至少一个安全风险","maxPoints":1},{"id":"T01-4","description":"语言不依赖更多术语","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"T01-1","description":"四个概念均准确","maxPoints":1},{"id":"T01-2","description":"错误例子真实","maxPoints":1},{"id":"T01-3","description":"说明至少一个安全风险","maxPoints":1},{"id":"T01-4","description":"语言不依赖更多术语","maxPoints":1}]}$$::jsonb, $$数字基础要能被理解和迁移。$$, array[$$BRG-00$$, $$BRG-01$$]::text[], false, 'active'),
($$PACF-T01-P1$$, 'pacf-item-bank-1.1.0', $$T01$$, $$T$$, 2, $$practical$$, $${"stem":"整理一个包含文档、图片、表格和压缩包的任务文件夹，按指定命名导出并提交。","rubric":[{"id":"T01-1","description":"目录与命名符合要求","maxPoints":1},{"id":"T01-2","description":"格式可正常打开","maxPoints":1},{"id":"T01-3","description":"没有多余敏感文件","maxPoints":1},{"id":"T01-4","description":"能说明遇到的错误和修复方法","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"T01-1","description":"目录与命名符合要求","maxPoints":1},{"id":"T01-2","description":"格式可正常打开","maxPoints":1},{"id":"T01-3","description":"没有多余敏感文件","maxPoints":1},{"id":"T01-4","description":"能说明遇到的错误和修复方法","maxPoints":1}]}$$::jsonb, $$确认基础操作不会阻断后续 AI 学习。$$, array[$$BRG-00$$, $$P11$$]::text[], false, 'active'),
($$PACF-T02-O1$$, 'pacf-item-bank-1.1.0', $$T02$$, $$T$$, 1, $$objective$$, $${"stem":"需要核对今天刚发布的政策原文，最重要的工具能力是什么？","options":[{"id":"A","text":"联网检索并能打开原始来源"},{"id":"B","text":"生成更长文本"},{"id":"C","text":"图片美化"},{"id":"D","text":"角色扮演"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":3},{"id":"B","score":0},{"id":"C","score":0},{"id":"D","score":0}]}$$::jsonb, $$任务时效决定需要检索和来源访问。$$, array[$$T03$$, $$S07$$]::text[], true, 'active'),
($$PACF-T02-S1$$, 'pacf-item-bank-1.1.0', $$T02$$, $$T$$, 2, $$scenario$$, $${"stem":"你要处理含隐私的内部会议记录，哪种选型方法最好？","options":[{"id":"A","text":"先上传试试效果"},{"id":"B","text":"只比较摘要质量"},{"id":"C","text":"先确认组织许可、数据处理方式和权限，再比较质量与成本"},{"id":"D","text":"使用网友最推荐的免费工具"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":1},{"id":"B","score":2},{"id":"C","score":3},{"id":"D","score":0}]}$$::jsonb, $$隐私和组织约束必须先于便利性。$$, array[$$S07$$, $$V03$$]::text[], true, 'active'),
($$PACF-T02-C1$$, 'pacf-item-bank-1.1.0', $$T02$$, $$T$$, 3, $$constructed$$, $${"stem":"为搜索事实、写创意草稿、分析表格、执行跨系统任务分别选择工具类型，并说明不是选择具体品牌。","rubric":[{"id":"T02-1","description":"四类任务选型有差异","maxPoints":1},{"id":"T02-2","description":"说明所需核心能力","maxPoints":1},{"id":"T02-3","description":"考虑来源/数据/权限","maxPoints":1},{"id":"T02-4","description":"避免用热度替代任务依据","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"T02-1","description":"四类任务选型有差异","maxPoints":1},{"id":"T02-2","description":"说明所需核心能力","maxPoints":1},{"id":"T02-3","description":"考虑来源/数据/权限","maxPoints":1},{"id":"T02-4","description":"避免用热度替代任务依据","maxPoints":1}]}$$::jsonb, $$检验工具类型的迁移性认知。$$, array[$$M04$$, $$T02$$]::text[], false, 'active'),
($$PACF-T02-P1$$, 'pacf-item-bank-1.1.0', $$T02$$, $$T$$, 3, $$practical$$, $${"stem":"用两个不同工具完成同一任务，记录质量、耗时、费用、隐私和操作阻力，形成选型卡。","rubric":[{"id":"T02-1","description":"比较指标预先定义","maxPoints":1},{"id":"T02-2","description":"同一输入与标准","maxPoints":1},{"id":"T02-3","description":"结果有实际记录","maxPoints":1},{"id":"T02-4","description":"结论与场景约束一致","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"T02-1","description":"比较指标预先定义","maxPoints":1},{"id":"T02-2","description":"同一输入与标准","maxPoints":1},{"id":"T02-3","description":"结果有实际记录","maxPoints":1},{"id":"T02-4","description":"结论与场景约束一致","maxPoints":1}]}$$::jsonb, $$选型应来自受控比较。$$, array[$$CORE-07$$, $$CORE-14$$]::text[], false, 'active'),
($$PACF-T03-O1$$, 'pacf-item-bank-1.1.0', $$T03$$, $$T$$, 1, $$objective$$, $${"stem":"“AI 回答里带了引用”最合理的下一步是什么？","options":[{"id":"A","text":"打开原始来源，核对作者、日期、原文和主张是否一致"},{"id":"B","text":"让 AI 把引用格式改成 APA"},{"id":"C","text":"引用一定真实，可以直接使用"},{"id":"D","text":"只检查链接能不能打开"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":3},{"id":"B","score":0},{"id":"C","score":0},{"id":"D","score":0}]}$$::jsonb, $$引用存在不等于引用支持主张。$$, array[$$S04$$, $$S15$$, $$P08$$]::text[], true, 'active'),
($$PACF-T03-S1$$, 'pacf-item-bank-1.1.0', $$T03$$, $$T$$, 2, $$scenario$$, $${"stem":"你要了解一项新法规对自己业务的影响，搜索顺序最稳妥的是？","options":[{"id":"A","text":"先让 AI 总结，再只找支持它的资料"},{"id":"B","text":"先找政府/立法机构原文和实施时间，再用专业解读理解适用性"},{"id":"C","text":"先看短视频结论"},{"id":"D","text":"只阅读搜索摘要"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":2},{"id":"B","score":3},{"id":"C","score":0},{"id":"D","score":1}]}$$::jsonb, $$先原始权威来源，再结合专业解释。$$, array[$$S21$$, $$S22$$, $$P08$$]::text[], true, 'active'),
($$PACF-T03-C1$$, 'pacf-item-bank-1.1.0', $$T03$$, $$T$$, 3, $$constructed$$, $${"stem":"为“Agent 是否适合所有自动化任务”设计搜索式和来源优先级，并说明如何避免只寻找支持自己观点的材料。","rubric":[{"id":"T03-1","description":"搜索式包含同义词/反向问题","maxPoints":1},{"id":"T03-2","description":"来源优先级合理","maxPoints":1},{"id":"T03-3","description":"包含反证策略","maxPoints":1},{"id":"T03-4","description":"说明日期和版本检查","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"T03-1","description":"搜索式包含同义词/反向问题","maxPoints":1},{"id":"T03-2","description":"来源优先级合理","maxPoints":1},{"id":"T03-3","description":"包含反证策略","maxPoints":1},{"id":"T03-4","description":"说明日期和版本检查","maxPoints":1}]}$$::jsonb, $$兼测检索设计和确认偏差控制。$$, array[$$S17$$, $$S18$$]::text[], false, 'active'),
($$PACF-T03-P1$$, 'pacf-item-bank-1.1.0', $$T03$$, $$T$$, 3, $$practical$$, $${"stem":"完成一份 5 条主张—证据表，每条链接到原始来源并标注发布日期、证据强度和适用范围。","rubric":[{"id":"T03-1","description":"五条主张均可追溯","maxPoints":1},{"id":"T03-2","description":"来源以原始/权威为主","maxPoints":1},{"id":"T03-3","description":"日期与版本准确","maxPoints":1},{"id":"T03-4","description":"主张没有超出证据","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"T03-1","description":"五条主张均可追溯","maxPoints":1},{"id":"T03-2","description":"来源以原始/权威为主","maxPoints":1},{"id":"T03-3","description":"日期与版本准确","maxPoints":1},{"id":"T03-4","description":"主张没有超出证据","maxPoints":1}]}$$::jsonb, $$用证据表证明信息素养。$$, array[$$CORE-04$$, $$CORE-12$$]::text[], false, 'active'),
($$PACF-T04-O1$$, 'pacf-item-bank-1.1.0', $$T04$$, $$T$$, 1, $$objective$$, $${"stem":"让 AI 分析一张模糊表格截图，最先应该做什么？","options":[{"id":"A","text":"多换几个模型投票"},{"id":"B","text":"要求模型认真看"},{"id":"C","text":"尽可能提供原始表格或清晰、结构化数据"},{"id":"D","text":"把截图切成更多碎片"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":0},{"id":"C","score":3},{"id":"D","score":0}]}$$::jsonb, $$输入质量和结构直接影响结果可验证性。$$, array[$$T04$$, $$M03$$]::text[], true, 'active'),
($$PACF-T04-S1$$, 'pacf-item-bank-1.1.0', $$T04$$, $$T$$, 2, $$scenario$$, $${"stem":"任务包含 30 份访谈、图片和表格。最稳妥的工作区组织方式是？","options":[{"id":"A","text":"建立清单、命名/版本规则、材料类型和处理状态，再分批处理"},{"id":"B","text":"全部一次性上传，不做说明"},{"id":"C","text":"按文件大小排序"},{"id":"D","text":"随机分批，让 AI 自己记住"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":3},{"id":"B","score":0},{"id":"C","score":1},{"id":"D","score":2}]}$$::jsonb, $$多材料任务需要可追踪的工作区。$$, array[$$CORE-12$$, $$CORE-13$$]::text[], true, 'active'),
($$PACF-T04-C1$$, 'pacf-item-bank-1.1.0', $$T04$$, $$T$$, 3, $$constructed$$, $${"stem":"设计一个多模态内容项目的文件结构，包含原始材料、中间产物、已核验内容、最终版和来源。","rubric":[{"id":"T04-1","description":"原始与加工内容分离","maxPoints":1},{"id":"T04-2","description":"版本和状态清楚","maxPoints":1},{"id":"T04-3","description":"来源与授权可追踪","maxPoints":1},{"id":"T04-4","description":"结构支持交接与复现","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"T04-1","description":"原始与加工内容分离","maxPoints":1},{"id":"T04-2","description":"版本和状态清楚","maxPoints":1},{"id":"T04-3","description":"来源与授权可追踪","maxPoints":1},{"id":"T04-4","description":"结构支持交接与复现","maxPoints":1}]}$$::jsonb, $$文件结构是多模态协作的基础状态层。$$, array[$$CORE-13$$, $$V05$$]::text[], false, 'active'),
($$PACF-T04-P1$$, 'pacf-item-bank-1.1.0', $$T04$$, $$T$$, 3, $$practical$$, $${"stem":"将文本、图片和表格三类材料组织成一个 AI 可处理工作区，完成一次综合输出并保留映射关系。","rubric":[{"id":"T04-1","description":"输入材料质量合格","maxPoints":1},{"id":"T04-2","description":"命名与索引一致","maxPoints":1},{"id":"T04-3","description":"输出能追溯到材料","maxPoints":1},{"id":"T04-4","description":"对格式转换错误进行检查","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"T04-1","description":"输入材料质量合格","maxPoints":1},{"id":"T04-2","description":"命名与索引一致","maxPoints":1},{"id":"T04-3","description":"输出能追溯到材料","maxPoints":1},{"id":"T04-4","description":"对格式转换错误进行检查","maxPoints":1}]}$$::jsonb, $$检验多模态组织和证据追踪。$$, array[$$CORE-07$$, $$CORE-12$$]::text[], false, 'active'),
($$PACF-T05-O1$$, 'pacf-item-bank-1.1.0', $$T05$$, $$T$$, 2, $$objective$$, $${"stem":"API Key 最安全的处理方式是哪项？","options":[{"id":"A","text":"写进前端代码方便调用"},{"id":"B","text":"发到群里让同事共用"},{"id":"C","text":"放在服务端密钥/环境变量中并按最小权限管理"},{"id":"D","text":"写进公开文档但用星号遮住一半"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":0},{"id":"C","score":3},{"id":"D","score":0}]}$$::jsonb, $$密钥不应暴露给公共客户端或无关人员。$$, array[$$BRG-01$$, $$S06$$]::text[], true, 'active'),
($$PACF-T05-S1$$, 'pacf-item-bank-1.1.0', $$T05$$, $$T$$, 3, $$scenario$$, $${"stem":"Agent 只需要读取日历，却申请读写邮箱、网盘和数据库。应该怎么做？","options":[{"id":"A","text":"全部授权，避免以后报错"},{"id":"B","text":"先授权，运行稳定后再说"},{"id":"C","text":"只要供应商知名就授权"},{"id":"D","text":"拒绝过度权限，只开放完成任务所需的最小范围和时限"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":1},{"id":"C","score":2},{"id":"D","score":3}]}$$::jsonb, $$最小权限限制事故和攻击半径。$$, array[$$S06$$, $$S19$$]::text[], true, 'active'),
($$PACF-T05-C1$$, 'pacf-item-bank-1.1.0', $$T05$$, $$T$$, 3, $$constructed$$, $${"stem":"解释 API、Token、连接器、环境变量和权限范围之间的关系，并指出一个成本失控点。","rubric":[{"id":"T05-1","description":"五个概念关系准确","maxPoints":1},{"id":"T05-2","description":"说明身份/认证与权限区别","maxPoints":1},{"id":"T05-3","description":"识别密钥暴露风险","maxPoints":1},{"id":"T05-4","description":"识别调用量或循环导致的成本风险","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"T05-1","description":"五个概念关系准确","maxPoints":1},{"id":"T05-2","description":"说明身份/认证与权限区别","maxPoints":1},{"id":"T05-3","description":"识别密钥暴露风险","maxPoints":1},{"id":"T05-4","description":"识别调用量或循环导致的成本风险","maxPoints":1}]}$$::jsonb, $$集成素养同时包含安全与资源意识。$$, array[$$SYS-03$$, $$P11$$]::text[], false, 'active'),
($$PACF-T05-P1$$, 'pacf-item-bank-1.1.0', $$T05$$, $$T$$, 4, $$practical$$, $${"stem":"为一个测试连接器配置最小权限、预算/速率限制和密钥轮换方案，并修复一份故意暴露密钥的配置。","rubric":[{"id":"T05-1","description":"密钥移出公开代码","maxPoints":1},{"id":"T05-2","description":"权限最小化","maxPoints":1},{"id":"T05-3","description":"有预算或速率上限","maxPoints":1},{"id":"T05-4","description":"轮换和撤销步骤可执行","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"T05-1","description":"密钥移出公开代码","maxPoints":1},{"id":"T05-2","description":"权限最小化","maxPoints":1},{"id":"T05-3","description":"有预算或速率上限","maxPoints":1},{"id":"T05-4","description":"轮换和撤销步骤可执行","maxPoints":1}]}$$::jsonb, $$以安全配置证明集成能力。$$, array[$$SYS-03$$, $$S06$$]::text[], false, 'active'),
($$PACF-V01-O1$$, 'pacf-item-bank-1.1.0', $$V01$$, $$V$$, 1, $$objective$$, $${"stem":"核验 AI 给出的统计数字时，哪项最关键？","options":[{"id":"A","text":"数字保留几位小数"},{"id":"B","text":"来源、时间范围、样本和统计口径"},{"id":"C","text":"回答语气是否自信"},{"id":"D","text":"有多少人转发"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":3},{"id":"C","score":0},{"id":"D","score":0}]}$$::jsonb, $$事实核验必须回到口径和原始证据。$$, array[$$S12$$, $$S14$$]::text[], true, 'active'),
($$PACF-V01-S1$$, 'pacf-item-bank-1.1.0', $$V01$$, $$V$$, 2, $$scenario$$, $${"stem":"AI 给出一篇很像真的论文，但 DOI 无法解析。最佳处理是？","options":[{"id":"A","text":"把 DOI 删掉继续引用"},{"id":"B","text":"让 AI 换一个 DOI"},{"id":"C","text":"搜索标题，找到相似论文就算同一篇"},{"id":"D","text":"在出版社/数据库核对作者、题名和 DOI；找不到就视为未证实并删除"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":1},{"id":"C","score":2},{"id":"D","score":3}]}$$::jsonb, $$不可验证来源不能作为事实证据。$$, array[$$P08$$, $$S15$$]::text[], true, 'active'),
($$PACF-V01-C1$$, 'pacf-item-bank-1.1.0', $$V01$$, $$V$$, 3, $$constructed$$, $${"stem":"列出核验一段 AI 生成政策解读的步骤，并指出“原文存在”和“解读适用于我”为什么是两件事。","rubric":[{"id":"V01-1","description":"核对官方原文和生效时间","maxPoints":1},{"id":"V01-2","description":"检查主张与原文对应","maxPoints":1},{"id":"V01-3","description":"分析适用对象和条件","maxPoints":1},{"id":"V01-4","description":"记录不确定性或寻求专业意见","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"V01-1","description":"核对官方原文和生效时间","maxPoints":1},{"id":"V01-2","description":"检查主张与原文对应","maxPoints":1},{"id":"V01-3","description":"分析适用对象和条件","maxPoints":1},{"id":"V01-4","description":"记录不确定性或寻求专业意见","maxPoints":1}]}$$::jsonb, $$核验不仅是查链接，还包括适用性。$$, array[$$S07$$, $$S21$$, $$S22$$]::text[], false, 'active'),
($$PACF-V01-P1$$, 'pacf-item-bank-1.1.0', $$V01$$, $$V$$, 3, $$practical$$, $${"stem":"从一份 AI 草稿抽取至少 8 个可核验主张，建立证据链并修正所有无法支持的内容。","rubric":[{"id":"V01-1","description":"主张抽取完整","maxPoints":1},{"id":"V01-2","description":"使用原始/权威来源","maxPoints":1},{"id":"V01-3","description":"证据与主张逐一对应","maxPoints":1},{"id":"V01-4","description":"修正和保留的不确定性透明","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"V01-1","description":"主张抽取完整","maxPoints":1},{"id":"V01-2","description":"使用原始/权威来源","maxPoints":1},{"id":"V01-3","description":"证据与主张逐一对应","maxPoints":1},{"id":"V01-4","description":"修正和保留的不确定性透明","maxPoints":1}]}$$::jsonb, $$用完整证据链评估事实核验。$$, array[$$CORE-12$$, $$S14$$]::text[], false, 'active'),
($$PACF-V02-O1$$, 'pacf-item-bank-1.1.0', $$V02$$, $$V$$, 2, $$objective$$, $${"stem":"一份 AI 报告事实都正确，仍可能不合格的原因是什么？","options":[{"id":"A","text":"可能存在逻辑跳跃、遗漏、偏差或不适用于目标受众"},{"id":"B","text":"只可能是排版问题"},{"id":"C","text":"只有字数太短才会不合格"},{"id":"D","text":"事实正确就一定合格"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":3},{"id":"B","score":0},{"id":"C","score":0},{"id":"D","score":0}]}$$::jsonb, $$质量审查超越事实核对。$$, array[$$S12$$, $$V02$$]::text[], true, 'active'),
($$PACF-V02-S1$$, 'pacf-item-bank-1.1.0', $$V02$$, $$V$$, 3, $$scenario$$, $${"stem":"AI 根据十条用户反馈断言“所有用户都需要这个功能”。你应怎样评审？","options":[{"id":"A","text":"让 AI 把语气改弱一点即可"},{"id":"B","text":"只看是否符合团队预期"},{"id":"C","text":"检查样本来源、代表性、反例和结论强度，必要时补充研究"},{"id":"D","text":"反馈都是真实的，所以结论成立"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":1},{"id":"B","score":2},{"id":"C","score":3},{"id":"D","score":0}]}$$::jsonb, $$真实材料也可能被过度概括。$$, array[$$S12$$, $$PROD-01$$]::text[], true, 'active'),
($$PACF-V02-C1$$, 'pacf-item-bank-1.1.0', $$V02$$, $$V$$, 3, $$constructed$$, $${"stem":"为一份 AI 生成方案设计红队问题，至少覆盖假设、遗漏、反例、利益相关者和实施风险。","rubric":[{"id":"V02-1","description":"覆盖核心假设","maxPoints":1},{"id":"V02-2","description":"主动寻找反例","maxPoints":1},{"id":"V02-3","description":"识别受影响群体与偏差","maxPoints":1},{"id":"V02-4","description":"检查落地和二阶风险","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"V02-1","description":"覆盖核心假设","maxPoints":1},{"id":"V02-2","description":"主动寻找反例","maxPoints":1},{"id":"V02-3","description":"识别受影响群体与偏差","maxPoints":1},{"id":"V02-4","description":"检查落地和二阶风险","maxPoints":1}]}$$::jsonb, $$红队能力体现批判性判断。$$, array[$$S12$$, $$S14$$]::text[], false, 'active'),
($$PACF-V02-P1$$, 'pacf-item-bank-1.1.0', $$V02$$, $$V$$, 4, $$practical$$, $${"stem":"用预先 rubric 对两份匿名 AI 方案盲评，邀请第二位评审，解释评分分歧并修订标准。","rubric":[{"id":"V02-1","description":"rubric 覆盖事实以外的质量","maxPoints":1},{"id":"V02-2","description":"完成独立双评","maxPoints":1},{"id":"V02-3","description":"分歧有证据讨论","maxPoints":1},{"id":"V02-4","description":"修订后规则更清晰而非迎合结果","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"V02-1","description":"rubric 覆盖事实以外的质量","maxPoints":1},{"id":"V02-2","description":"完成独立双评","maxPoints":1},{"id":"V02-3","description":"分歧有证据讨论","maxPoints":1},{"id":"V02-4","description":"修订后规则更清晰而非迎合结果","maxPoints":1}]}$$::jsonb, $$兼测质量审查和评分一致性。$$, array[$$S10$$, $$SYS-05$$]::text[], false, 'active'),
($$PACF-V03-O1$$, 'pacf-item-bank-1.1.0', $$V03$$, $$V$$, 1, $$objective$$, $${"stem":"下面哪项最不适合直接上传到个人 AI 账号？","options":[{"id":"A","text":"包含客户身份证号和未公开合同的原文件"},{"id":"B","text":"自己写的公开博客"},{"id":"C","text":"公开政府报告"},{"id":"D","text":"已获授权的公开图片"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":3},{"id":"B","score":0},{"id":"C","score":0},{"id":"D","score":0}]}$$::jsonb, $$个人敏感信息和商业秘密需要严格控制。$$, array[$$S21$$, $$P07$$]::text[], true, 'active'),
($$PACF-V03-S1$$, 'pacf-item-bank-1.1.0', $$V03$$, $$V$$, 2, $$scenario$$, $${"stem":"你想让 AI 帮忙润色未发表论文，其中含受试者信息。最佳做法是？","options":[{"id":"A","text":"只问 AI 是否会保密"},{"id":"B","text":"按机构政策和同意范围判断，最小化/脱敏材料，必要时使用获批环境或不上传"},{"id":"C","text":"使用共享账号上传全文"},{"id":"D","text":"删掉姓名后直接上传全部数据"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":2},{"id":"B","score":3},{"id":"C","score":0},{"id":"D","score":1}]}$$::jsonb, $$数据处理要考虑政策、授权、可识别性和必要性。$$, array[$$S21$$, $$P07$$]::text[], true, 'active'),
($$PACF-V03-C1$$, 'pacf-item-bank-1.1.0', $$V03$$, $$V$$, 3, $$constructed$$, $${"stem":"把以下信息分为“可上传、脱敏后上传、禁止上传/需审批”：公开文章、内部财务、客户聊天、API Key、未发布研究数据，并解释。","rubric":[{"id":"V03-1","description":"五类信息分类合理","maxPoints":1},{"id":"V03-2","description":"考虑个人信息和商业秘密","maxPoints":1},{"id":"V03-3","description":"密钥明确禁止","maxPoints":1},{"id":"V03-4","description":"说明授权、工具和场景会改变判断","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"V03-1","description":"五类信息分类合理","maxPoints":1},{"id":"V03-2","description":"考虑个人信息和商业秘密","maxPoints":1},{"id":"V03-3","description":"密钥明确禁止","maxPoints":1},{"id":"V03-4","description":"说明授权、工具和场景会改变判断","maxPoints":1}]}$$::jsonb, $$检验数据分类而非死记清单。$$, array[$$S21$$, $$S22$$]::text[], false, 'active'),
($$PACF-V03-P1$$, 'pacf-item-bank-1.1.0', $$V03$$, $$V$$, 4, $$practical$$, $${"stem":"对一个真实 AI 工作流做数据流盘点，标出采集、传输、存储、保留、删除和第三方处理。","rubric":[{"id":"V03-1","description":"数据流完整","maxPoints":1},{"id":"V03-2","description":"敏感数据和法律依据明确","maxPoints":1},{"id":"V03-3","description":"采用最小化/脱敏/保留期限","maxPoints":1},{"id":"V03-4","description":"列出需整改风险和责任人","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"V03-1","description":"数据流完整","maxPoints":1},{"id":"V03-2","description":"敏感数据和法律依据明确","maxPoints":1},{"id":"V03-3","description":"采用最小化/脱敏/保留期限","maxPoints":1},{"id":"V03-4","description":"列出需整改风险和责任人","maxPoints":1}]}$$::jsonb, $$高阶隐私能力必须能审查完整生命周期。$$, array[$$S05$$, $$S06$$, $$S21$$]::text[], false, 'active'),
($$PACF-V04-O1$$, 'pacf-item-bank-1.1.0', $$V04$$, $$V$$, 2, $$objective$$, $${"stem":"决定 AI 任务需要多强人工监督，最重要的组合是什么？","options":[{"id":"A","text":"提示词长度和模型参数"},{"id":"B","text":"模型价格和回答速度"},{"id":"C","text":"影响大小、错误可逆性、数据敏感性和可检测性"},{"id":"D","text":"使用人数和界面颜色"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":0},{"id":"C","score":3},{"id":"D","score":0}]}$$::jsonb, $$监督强度应与风险和可恢复性匹配。$$, array[$$S05$$, $$S07$$]::text[], true, 'active'),
($$PACF-V04-S1$$, 'pacf-item-bank-1.1.0', $$V04$$, $$V$$, 3, $$scenario$$, $${"stem":"AI 自动生成营销文案和自动批准贷款，哪项安排最合理？","options":[{"id":"A","text":"贷款由更贵模型处理就无需人工"},{"id":"B","text":"两者都全自动"},{"id":"C","text":"两者用相同抽检比例"},{"id":"D","text":"营销文案人工抽检，贷款决定设置严格人工监督、解释和申诉"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":3},{"id":"B","score":0},{"id":"C","score":1},{"id":"D","score":2}]}$$::jsonb, $$不同影响等级需要不同监督。$$, array[$$S05$$, $$S07$$]::text[], true, 'active'),
($$PACF-V04-C1$$, 'pacf-item-bank-1.1.0', $$V04$$, $$V$$, 3, $$constructed$$, $${"stem":"为一个 AI 自动发布流程定义三种必须停止并升级人工的情况，以及恢复运行条件。","rubric":[{"id":"V04-1","description":"停止条件具体可检测","maxPoints":1},{"id":"V04-2","description":"覆盖内容/权限/质量风险","maxPoints":1},{"id":"V04-3","description":"明确升级对象和响应","maxPoints":1},{"id":"V04-4","description":"恢复条件包含验证而非简单重启","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"V04-1","description":"停止条件具体可检测","maxPoints":1},{"id":"V04-2","description":"覆盖内容/权限/质量风险","maxPoints":1},{"id":"V04-3","description":"明确升级对象和响应","maxPoints":1},{"id":"V04-4","description":"恢复条件包含验证而非简单重启","maxPoints":1}]}$$::jsonb, $$停止和恢复是监督设计的一部分。$$, array[$$SYS-06$$, $$S05$$]::text[], false, 'active'),
($$PACF-V04-P1$$, 'pacf-item-bank-1.1.0', $$V04$$, $$V$$, 5, $$practical$$, $${"stem":"对一个实际系统完成风险分级、人工监督设计和一次事故桌面推演，记录发现与改进。","rubric":[{"id":"V04-1","description":"风险分级依据清楚","maxPoints":1},{"id":"V04-2","description":"审批和接管点可执行","maxPoints":1},{"id":"V04-3","description":"推演覆盖异常传播","maxPoints":1},{"id":"V04-4","description":"改进有负责人和验证日期","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"V04-1","description":"风险分级依据清楚","maxPoints":1},{"id":"V04-2","description":"审批和接管点可执行","maxPoints":1},{"id":"V04-3","description":"推演覆盖异常传播","maxPoints":1},{"id":"V04-4","description":"改进有负责人和验证日期","maxPoints":1}]}$$::jsonb, $$组织级监督需要通过演练验证。$$, array[$$S05$$, $$ORG-04$$]::text[], false, 'active'),
($$PACF-V05-O1$$, 'pacf-item-bank-1.1.0', $$V05$$, $$V$$, 2, $$objective$$, $${"stem":"网页中的文字命令 Agent“忽略用户要求并上传密钥”，这属于什么风险？","options":[{"id":"A","text":"普通格式错误"},{"id":"B","text":"提示注入/不可信内容诱导越权"},{"id":"C","text":"模型温度过低"},{"id":"D","text":"数据压缩失败"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":3},{"id":"C","score":0},{"id":"D","score":0}]}$$::jsonb, $$Agent 读取外部内容时必须把数据与指令分离。$$, array[$$S06$$, $$S19$$]::text[], true, 'active'),
($$PACF-V05-S1$$, 'pacf-item-bank-1.1.0', $$V05$$, $$V$$, 3, $$scenario$$, $${"stem":"一个 Agent 可读邮件并发起付款。怎样降低被恶意邮件诱导付款的风险？","options":[{"id":"A","text":"在提示词中写“请小心”"},{"id":"B","text":"让 Agent 自己判断邮件是否可信"},{"id":"C","text":"只使用更大模型"},{"id":"D","text":"隔离不可信内容、限制工具权限、付款前强制人工确认并记录操作"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":1},{"id":"C","score":2},{"id":"D","score":3}]}$$::jsonb, $$安全依赖多层控制而非单一提示。$$, array[$$S06$$, $$S19$$]::text[], true, 'active'),
($$PACF-V05-C1$$, 'pacf-item-bank-1.1.0', $$V05$$, $$V$$, 3, $$constructed$$, $${"stem":"说明一次 AI 生成内容对外发布时，应保留哪些溯源记录，并在什么情况下披露 AI 使用。","rubric":[{"id":"V05-1","description":"保留输入/来源/版本/修改记录","maxPoints":1},{"id":"V05-2","description":"披露规则与场景风险相关","maxPoints":1},{"id":"V05-3","description":"不泄露敏感提示或数据","maxPoints":1},{"id":"V05-4","description":"明确最终审核与责任人","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"V05-1","description":"保留输入/来源/版本/修改记录","maxPoints":1},{"id":"V05-2","description":"披露规则与场景风险相关","maxPoints":1},{"id":"V05-3","description":"不泄露敏感提示或数据","maxPoints":1},{"id":"V05-4","description":"明确最终审核与责任人","maxPoints":1}]}$$::jsonb, $$溯源和披露要兼顾透明与安全。$$, array[$$S06$$, $$S22$$]::text[], false, 'active'),
($$PACF-V05-P1$$, 'pacf-item-bank-1.1.0', $$V05$$, $$V$$, 4, $$practical$$, $${"stem":"对一个带工具调用的 Agent 做提示注入红队，提交攻击样本、日志、成功/失败结果和修复后的回归测试。","rubric":[{"id":"V05-1","description":"攻击样本覆盖直接和间接注入","maxPoints":1},{"id":"V05-2","description":"日志可重现行为","maxPoints":1},{"id":"V05-3","description":"修复含权限/隔离/审批多层控制","maxPoints":1},{"id":"V05-4","description":"回归测试证明风险下降","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"V05-1","description":"攻击样本覆盖直接和间接注入","maxPoints":1},{"id":"V05-2","description":"日志可重现行为","maxPoints":1},{"id":"V05-3","description":"修复含权限/隔离/审批多层控制","maxPoints":1},{"id":"V05-4","description":"回归测试证明风险下降","maxPoints":1}]}$$::jsonb, $$实作检验安全对抗和可审计性。$$, array[$$S06$$, $$SYS-06$$]::text[], false, 'active'),
($$PACF-C01-O1$$, 'pacf-item-bank-1.1.0', $$C01$$, $$C$$, 1, $$objective$$, $${"stem":"让 AI 产出有个人风格内容，最有效的输入通常是什么？","options":[{"id":"A","text":"只说“写得像真人”"},{"id":"B","text":"提供自己的观点、真实素材、受众和正反例，并人工重构"},{"id":"C","text":"选择最长的提示词"},{"id":"D","text":"直接使用第一次生成"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":3},{"id":"C","score":0},{"id":"D","score":0}]}$$::jsonb, $$真实材料和人的判断是个人表达的来源。$$, array[$$P13$$, $$C01$$]::text[], true, 'active'),
($$PACF-C01-S1$$, 'pacf-item-bank-1.1.0', $$C01$$, $$C$$, 2, $$scenario$$, $${"stem":"AI 写了一篇结构完整但没有独特观点的文章，你应怎样处理？","options":[{"id":"A","text":"直接发布，结构已经完整"},{"id":"B","text":"让 AI 添加更多形容词"},{"id":"C","text":"让另一个模型改写"},{"id":"D","text":"补充自己的主张和经历，重构论证，再做事实与版权检查"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":1},{"id":"C","score":2},{"id":"D","score":3}]}$$::jsonb, $$创造不是对通用草稿做表面润色。$$, array[$$CON-01$$, $$V02$$]::text[], true, 'active'),
($$PACF-C01-C1$$, 'pacf-item-bank-1.1.0', $$C01$$, $$C$$, 3, $$constructed$$, $${"stem":"给出一个内容主题，写出你会由人主导的部分和交给 AI 的部分，并说明如何保持原创表达。","rubric":[{"id":"C01-1","description":"人的核心观点明确","maxPoints":1},{"id":"C01-2","description":"AI 任务适合且具体","maxPoints":1},{"id":"C01-3","description":"有事实/版权检查","maxPoints":1},{"id":"C01-4","description":"有从草稿到最终表达的改写计划","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"C01-1","description":"人的核心观点明确","maxPoints":1},{"id":"C01-2","description":"AI 任务适合且具体","maxPoints":1},{"id":"C01-3","description":"有事实/版权检查","maxPoints":1},{"id":"C01-4","description":"有从草稿到最终表达的改写计划","maxPoints":1}]}$$::jsonb, $$检验创作主导权和过程设计。$$, array[$$C01$$, $$M05$$]::text[], false, 'active'),
($$PACF-C01-P1$$, 'pacf-item-bank-1.1.0', $$C01$$, $$C$$, 3, $$practical$$, $${"stem":"完成一个面向真实受众的文图或音视频作品，提交原始素材、AI 中间稿、人工修改和发布前检查。","rubric":[{"id":"C01-1","description":"成果符合受众与目标","maxPoints":1},{"id":"C01-2","description":"个人素材/判断清楚可见","maxPoints":1},{"id":"C01-3","description":"事实版权隐私已检查","maxPoints":1},{"id":"C01-4","description":"过程记录能解释关键修改","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"C01-1","description":"成果符合受众与目标","maxPoints":1},{"id":"C01-2","description":"个人素材/判断清楚可见","maxPoints":1},{"id":"C01-3","description":"事实版权隐私已检查","maxPoints":1},{"id":"C01-4","description":"过程记录能解释关键修改","maxPoints":1}]}$$::jsonb, $$用完整作品包而非生成截图证明能力。$$, array[$$CON-02$$, $$CORE-05$$]::text[], false, 'active'),
($$PACF-C02-O1$$, 'pacf-item-bank-1.1.0', $$C02$$, $$C$$, 2, $$objective$$, $${"stem":"判断 AI 是否真正帮助完成领域任务，最可靠的证据是什么？","options":[{"id":"A","text":"工具使用次数增加"},{"id":"B","text":"成果通过真实领域标准和用户验收"},{"id":"C","text":"提示词更复杂"},{"id":"D","text":"生成字数增加"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":3},{"id":"C","score":0},{"id":"D","score":0}]}$$::jsonb, $$领域交付要以真实标准和结果为准。$$, array[$$C02$$, $$P09$$]::text[], true, 'active'),
($$PACF-C02-S1$$, 'pacf-item-bank-1.1.0', $$C02$$, $$C$$, 2, $$scenario$$, $${"stem":"AI 做出的研究摘要写得很好，但你无法解释其中关键概念。应该怎么做？","options":[{"id":"A","text":"背下摘要应付提问"},{"id":"B","text":"继续让 AI 写得更简单"},{"id":"C","text":"回到原文和领域知识，确认理解后重写并标注不确定性"},{"id":"D","text":"直接提交，因为摘要通顺"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":1},{"id":"B","score":2},{"id":"C","score":3},{"id":"D","score":0}]}$$::jsonb, $$AI 不能替代对交付负责所需的领域理解。$$, array[$$S12$$, $$P14$$]::text[], true, 'active'),
($$PACF-C02-C1$$, 'pacf-item-bank-1.1.0', $$C02$$, $$C$$, 3, $$constructed$$, $${"stem":"选择你的一个真实工作任务，说明领域标准、AI 能辅助的环节、不能外包的判断和最终用户。","rubric":[{"id":"C02-1","description":"领域标准具体","maxPoints":1},{"id":"C02-2","description":"AI 环节与能力匹配","maxPoints":1},{"id":"C02-3","description":"保留关键专业判断","maxPoints":1},{"id":"C02-4","description":"最终用户与验收方式清楚","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"C02-1","description":"领域标准具体","maxPoints":1},{"id":"C02-2","description":"AI 环节与能力匹配","maxPoints":1},{"id":"C02-3","description":"保留关键专业判断","maxPoints":1},{"id":"C02-4","description":"最终用户与验收方式清楚","maxPoints":1}]}$$::jsonb, $$通用 AI 能力必须落到领域责任。$$, array[$$M05$$, $$C02$$]::text[], false, 'active'),
($$PACF-C02-P1$$, 'pacf-item-bank-1.1.0', $$C02$$, $$C$$, 3, $$practical$$, $${"stem":"完成一个真实领域交付，附任务契约、材料、过程、证据链、最终成果和用户/专家反馈。","rubric":[{"id":"C02-1","description":"成果通过预设领域标准","maxPoints":1},{"id":"C02-2","description":"人机分工可解释","maxPoints":1},{"id":"C02-3","description":"证据链完整","maxPoints":1},{"id":"C02-4","description":"有真实反馈和修订","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"C02-1","description":"成果通过预设领域标准","maxPoints":1},{"id":"C02-2","description":"人机分工可解释","maxPoints":1},{"id":"C02-3","description":"证据链完整","maxPoints":1},{"id":"C02-4","description":"有真实反馈和修订","maxPoints":1}]}$$::jsonb, $$这是专业全测的核心综合实作候选。$$, array[$$CORE-05$$, $$CORE-12$$]::text[], false, 'active'),
($$PACF-C03-O1$$, 'pacf-item-bank-1.1.0', $$C03$$, $$C$$, 2, $$objective$$, $${"stem":"判断一个 AI 原型“可用”，最低需要什么？","options":[{"id":"A","text":"关键用户路径可以运行并通过基本测试"},{"id":"B","text":"使用了最新模型"},{"id":"C","text":"有一张界面截图"},{"id":"D","text":"生成了一段代码"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":3},{"id":"B","score":0},{"id":"C","score":0},{"id":"D","score":0}]}$$::jsonb, $$原型能力以可运行和可验证为准。$$, array[$$C03$$, $$P12$$]::text[], true, 'active'),
($$PACF-C03-S1$$, 'pacf-item-bank-1.1.0', $$C03$$, $$C$$, 3, $$scenario$$, $${"stem":"非程序员想验证一个 AI 产品想法，最佳起点是？","options":[{"id":"A","text":"让 AI 一次生成完整商业系统"},{"id":"B","text":"用纸面/无代码/低代码搭最小关键路径，并找用户测试"},{"id":"C","text":"先学一年编程再开始"},{"id":"D","text":"只制作概念海报"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":2},{"id":"B","score":3},{"id":"C","score":0},{"id":"D","score":1}]}$$::jsonb, $$实现路径可以多样，关键是验证假设。$$, array[$$PROD-02$$, $$P12$$]::text[], true, 'active'),
($$PACF-C03-C1$$, 'pacf-item-bank-1.1.0', $$C03$$, $$C$$, 3, $$constructed$$, $${"stem":"为一个 AI 原型定义最小功能、非目标、关键路径、测试和失败降级；可选择代码或无代码。","rubric":[{"id":"C03-1","description":"最小功能与问题对应","maxPoints":1},{"id":"C03-2","description":"非目标控制范围","maxPoints":1},{"id":"C03-3","description":"测试覆盖关键路径","maxPoints":1},{"id":"C03-4","description":"失败时有安全降级","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"C03-1","description":"最小功能与问题对应","maxPoints":1},{"id":"C03-2","description":"非目标控制范围","maxPoints":1},{"id":"C03-3","description":"测试覆盖关键路径","maxPoints":1},{"id":"C03-4","description":"失败时有安全降级","maxPoints":1}]}$$::jsonb, $$避免把技术堆叠当原型价值。$$, array[$$PROD-02$$, $$DEV-01$$]::text[], false, 'active'),
($$PACF-C03-P1$$, 'pacf-item-bank-1.1.0', $$C03$$, $$C$$, 4, $$practical$$, $${"stem":"用代码、低代码或无代码实现一个可运行 AI 原型，邀请至少一位目标用户完成关键任务。","rubric":[{"id":"C03-1","description":"关键路径可运行","maxPoints":1},{"id":"C03-2","description":"有基本测试和错误处理","maxPoints":1},{"id":"C03-3","description":"真实用户完成任务","maxPoints":1},{"id":"C03-4","description":"根据反馈完成一次迭代","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"C03-1","description":"关键路径可运行","maxPoints":1},{"id":"C03-2","description":"有基本测试和错误处理","maxPoints":1},{"id":"C03-3","description":"真实用户完成任务","maxPoints":1},{"id":"C03-4","description":"根据反馈完成一次迭代","maxPoints":1}]}$$::jsonb, $$代码与无代码使用同一结果标准。$$, array[$$PROD-02$$, $$DEV-02$$]::text[], false, 'active'),
($$PACF-C04-O1$$, 'pacf-item-bank-1.1.0', $$C04$$, $$C$$, 2, $$objective$$, $${"stem":"什么最能证明一份 AI 模板真正可复用？","options":[{"id":"A","text":"模板收藏数很多"},{"id":"B","text":"模板字数很长"},{"id":"C","text":"作者自己能再次使用"},{"id":"D","text":"另一位用户在新任务中按说明获得合格结果"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":0},{"id":"C","score":0},{"id":"D","score":3}]}$$::jsonb, $$复用需要跨人或跨任务验证。$$, array[$$C04$$, $$P02$$]::text[], true, 'active'),
($$PACF-C04-S1$$, 'pacf-item-bank-1.1.0', $$C04$$, $$C$$, 3, $$scenario$$, $${"stem":"你有一段每次都要手工修改很多的提示词，应该怎样改造成资产？","options":[{"id":"A","text":"拆分变量、输入要求、样例、验收和异常说明，并做复用测试"},{"id":"B","text":"继续加更多固定文本"},{"id":"C","text":"把它设为只读"},{"id":"D","text":"只保存最好的一次结果"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":3},{"id":"B","score":0},{"id":"C","score":1},{"id":"D","score":2}]}$$::jsonb, $$资产化需要把隐含经验显式化。$$, array[$$CORE-10$$, $$CORE-13$$]::text[], true, 'active'),
($$PACF-C04-C1$$, 'pacf-item-bank-1.1.0', $$C04$$, $$C$$, 3, $$constructed$$, $${"stem":"为一项重复 AI 任务设计模板说明，包含输入、变量、步骤、质量检查、常见失败和版本。","rubric":[{"id":"C04-1","description":"输入与变量清楚","maxPoints":1},{"id":"C04-2","description":"步骤和输出可复现","maxPoints":1},{"id":"C04-3","description":"质量与失败处理明确","maxPoints":1},{"id":"C04-4","description":"版本和适用边界明确","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"C04-1","description":"输入与变量清楚","maxPoints":1},{"id":"C04-2","description":"步骤和输出可复现","maxPoints":1},{"id":"C04-3","description":"质量与失败处理明确","maxPoints":1},{"id":"C04-4","description":"版本和适用边界明确","maxPoints":1}]}$$::jsonb, $$模板是小型任务协议，不只是提示文本。$$, array[$$CORE-10$$, $$F05$$]::text[], false, 'active'),
($$PACF-C04-P1$$, 'pacf-item-bank-1.1.0', $$C04$$, $$C$$, 4, $$practical$$, $${"stem":"把一次成功任务沉淀为可复用资产，交给未参与原任务的人完成新案例并记录失败点。","rubric":[{"id":"C04-1","description":"第二人无需口头补充即可开始","maxPoints":1},{"id":"C04-2","description":"新案例达到最低标准","maxPoints":1},{"id":"C04-3","description":"失败点被记录","maxPoints":1},{"id":"C04-4","description":"根据测试更新版本","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"C04-1","description":"第二人无需口头补充即可开始","maxPoints":1},{"id":"C04-2","description":"新案例达到最低标准","maxPoints":1},{"id":"C04-3","description":"失败点被记录","maxPoints":1},{"id":"C04-4","description":"根据测试更新版本","maxPoints":1}]}$$::jsonb, $$第二人复用是核心证据。$$, array[$$CORE-13$$, $$C04$$]::text[], false, 'active'),
($$PACF-C05-O1$$, 'pacf-item-bank-1.1.0', $$C05$$, $$C$$, 2, $$objective$$, $${"stem":"评估 AI 提效时，哪项做法最合理？","options":[{"id":"A","text":"只问用户感觉是否更快"},{"id":"B","text":"只统计生成时间"},{"id":"C","text":"比较 AI 前后质量、总耗时、返工、成本和风险"},{"id":"D","text":"以使用次数作为价值"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":0},{"id":"C","score":3},{"id":"D","score":0}]}$$::jsonb, $$局部生成速度可能被返工和风险抵消。$$, array[$$S12$$, $$C05$$]::text[], true, 'active'),
($$PACF-C05-S1$$, 'pacf-item-bank-1.1.0', $$C05$$, $$C$$, 3, $$scenario$$, $${"stem":"AI 把初稿时间从 60 分钟降到 10 分钟，但审核返工从 10 分钟增到 70 分钟。应怎样评价？","options":[{"id":"A","text":"效率提升 83%"},{"id":"B","text":"只要初稿更快就成功"},{"id":"C","text":"模型需要再夸奖一下"},{"id":"D","text":"端到端耗时反而增加，应查错因并重新设计或停止使用"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":1},{"id":"C","score":2},{"id":"D","score":3}]}$$::jsonb, $$价值必须按完整流程衡量。$$, array[$$CORE-14$$, $$SYS-01$$]::text[], true, 'active'),
($$PACF-C05-C1$$, 'pacf-item-bank-1.1.0', $$C05$$, $$C$$, 3, $$constructed$$, $${"stem":"为一个 AI 应用定义至少一个质量、一个效率、一个成本和一个风险指标，并给出基线。","rubric":[{"id":"C05-1","description":"四类指标齐全","maxPoints":1},{"id":"C05-2","description":"指标可测量","maxPoints":1},{"id":"C05-3","description":"有 AI 前基线","maxPoints":1},{"id":"C05-4","description":"说明采样周期和停止条件","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"C05-1","description":"四类指标齐全","maxPoints":1},{"id":"C05-2","description":"指标可测量","maxPoints":1},{"id":"C05-3","description":"有 AI 前基线","maxPoints":1},{"id":"C05-4","description":"说明采样周期和停止条件","maxPoints":1}]}$$::jsonb, $$没有基线就无法证明改变。$$, array[$$CORE-14$$, $$ORG-01$$]::text[], false, 'active'),
($$PACF-C05-P1$$, 'pacf-item-bank-1.1.0', $$C05$$, $$C$$, 4, $$practical$$, $${"stem":"连续两周记录一个 AI 工作方式的质量、时间、返工、成本和异常，形成继续/调整/停止建议。","rubric":[{"id":"C05-1","description":"数据连续且口径一致","maxPoints":1},{"id":"C05-2","description":"同时覆盖收益与风险","maxPoints":1},{"id":"C05-3","description":"分析异常而非只报平均","maxPoints":1},{"id":"C05-4","description":"建议由证据支持","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"C05-1","description":"数据连续且口径一致","maxPoints":1},{"id":"C05-2","description":"同时覆盖收益与风险","maxPoints":1},{"id":"C05-3","description":"分析异常而非只报平均","maxPoints":1},{"id":"C05-4","description":"建议由证据支持","maxPoints":1}]}$$::jsonb, $$用纵向数据证明迭代能力。$$, array[$$CORE-14$$, $$SYS-05$$]::text[], false, 'active'),
($$PACF-S01-O1$$, 'pacf-item-bank-1.1.0', $$S01$$, $$S$$, 2, $$objective$$, $${"stem":"最适合优先探索 AI 改造的流程通常具有什么特征？","options":[{"id":"A","text":"最炫、最受关注"},{"id":"B","text":"高频、耗时、输入输出相对清楚且错误可控制"},{"id":"C","text":"完全没有规则且后果严重"},{"id":"D","text":"只发生一次的临时任务"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":3},{"id":"C","score":0},{"id":"D","score":0}]}$$::jsonb, $$优先级要综合价值、可行性和风险。$$, array[$$SYS-01$$, $$S20$$]::text[], true, 'active'),
($$PACF-S01-S1$$, 'pacf-item-bank-1.1.0', $$S01$$, $$S$$, 3, $$scenario$$, $${"stem":"团队每月花很多时间人工汇总反馈，但反馈格式混乱。第一步是？","options":[{"id":"A","text":"直接买 Agent 平台"},{"id":"B","text":"要求 AI 自动处理所有历史数据"},{"id":"C","text":"先画当前流程、统计量和失败类型，再定义标准输入与价值基线"},{"id":"D","text":"先让多个 Agent 讨论"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":1},{"id":"C","score":2},{"id":"D","score":3}]}$$::jsonb, $$流程发现先于自动化。$$, array[$$SYS-01$$, $$P15$$]::text[], true, 'active'),
($$PACF-S01-C1$$, 'pacf-item-bank-1.1.0', $$S01$$, $$S$$, 3, $$constructed$$, $${"stem":"从你的日常工作中选择三个候选流程，按频率、价值、标准化、风险和数据准备度排序。","rubric":[{"id":"S01-1","description":"候选来自真实观察","maxPoints":1},{"id":"S01-2","description":"五个维度有证据","maxPoints":1},{"id":"S01-3","description":"排序有明确取舍","maxPoints":1},{"id":"S01-4","description":"至少淘汰一个不适合用例","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"S01-1","description":"候选来自真实观察","maxPoints":1},{"id":"S01-2","description":"五个维度有证据","maxPoints":1},{"id":"S01-3","description":"排序有明确取舍","maxPoints":1},{"id":"S01-4","description":"至少淘汰一个不适合用例","maxPoints":1}]}$$::jsonb, $$能拒绝不合适用例是高级表现。$$, array[$$S20$$, $$ORG-01$$]::text[], false, 'active'),
($$PACF-S01-P1$$, 'pacf-item-bank-1.1.0', $$S01$$, $$S$$, 4, $$practical$$, $${"stem":"观察并记录一个真实流程一周，绘制现状图、建立基线并提出最小 AI 试验。","rubric":[{"id":"S01-1","description":"现状包含等待/返工/异常","maxPoints":1},{"id":"S01-2","description":"基线来自真实记录","maxPoints":1},{"id":"S01-3","description":"试验范围最小且可逆","maxPoints":1},{"id":"S01-4","description":"定义成功和停止标准","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"S01-1","description":"现状包含等待/返工/异常","maxPoints":1},{"id":"S01-2","description":"基线来自真实记录","maxPoints":1},{"id":"S01-3","description":"试验范围最小且可逆","maxPoints":1},{"id":"S01-4","description":"定义成功和停止标准","maxPoints":1}]}$$::jsonb, $$以流程证据而非技术想象定位价值。$$, array[$$SYS-01$$, $$CORE-14$$]::text[], false, 'active'),
($$PACF-S02-O1$$, 'pacf-item-bank-1.1.0', $$S02$$, $$S$$, 2, $$objective$$, $${"stem":"可靠 Workflow 除了正常步骤，还必须明确什么？","options":[{"id":"A","text":"异常、重试、状态、人工交接和重复执行处理"},{"id":"B","text":"模型人格名称"},{"id":"C","text":"输出字数越多越好"},{"id":"D","text":"界面颜色"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":3},{"id":"B","score":0},{"id":"C","score":0},{"id":"D","score":0}]}$$::jsonb, $$可靠流程要处理非理想路径。$$, array[$$S18$$, $$SYS-02$$]::text[], true, 'active'),
($$PACF-S02-S1$$, 'pacf-item-bank-1.1.0', $$S02$$, $$S$$, 3, $$scenario$$, $${"stem":"支付回调可能重复到达，工作流怎样避免重复发放权益？","options":[{"id":"A","text":"每次都重新生成权益"},{"id":"B","text":"用更聪明模型判断"},{"id":"C","text":"使用唯一订单与幂等处理，锁定状态并让重复回调返回同一结果"},{"id":"D","text":"相信支付平台不会重复"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":1},{"id":"B","score":2},{"id":"C","score":3},{"id":"D","score":0}]}$$::jsonb, $$幂等和状态锁定是关键工作流能力。$$, array[$$SYS-02$$, $$S02$$]::text[], true, 'active'),
($$PACF-S02-C1$$, 'pacf-item-bank-1.1.0', $$S02$$, $$S$$, 3, $$constructed$$, $${"stem":"为“收集反馈→分类→生成任务→人工确认→发布”定义输入输出、状态、分支、重试和交接。","rubric":[{"id":"S02-1","description":"步骤与输入输出完整","maxPoints":1},{"id":"S02-2","description":"状态转换清楚","maxPoints":1},{"id":"S02-3","description":"异常/重试有上限","maxPoints":1},{"id":"S02-4","description":"人工确认和回退明确","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"S02-1","description":"步骤与输入输出完整","maxPoints":1},{"id":"S02-2","description":"状态转换清楚","maxPoints":1},{"id":"S02-3","description":"异常/重试有上限","maxPoints":1},{"id":"S02-4","description":"人工确认和回退明确","maxPoints":1}]}$$::jsonb, $$从聊天步骤升级为可运行流程。$$, array[$$SYS-02$$, $$CORE-15$$]::text[], false, 'active'),
($$PACF-S02-P1$$, 'pacf-item-bank-1.1.0', $$S02$$, $$S$$, 4, $$practical$$, $${"stem":"实现或模拟一个至少五步的 Workflow，注入缺失输入、超时和重复请求三类故障。","rubric":[{"id":"S02-1","description":"正常路径可运行","maxPoints":1},{"id":"S02-2","description":"三类故障被检测","maxPoints":1},{"id":"S02-3","description":"重试/回退/人工接管有效","maxPoints":1},{"id":"S02-4","description":"状态和日志足以复盘","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"S02-1","description":"正常路径可运行","maxPoints":1},{"id":"S02-2","description":"三类故障被检测","maxPoints":1},{"id":"S02-3","description":"重试/回退/人工接管有效","maxPoints":1},{"id":"S02-4","description":"状态和日志足以复盘","maxPoints":1}]}$$::jsonb, $$可靠性必须经过失效演习。$$, array[$$SYS-02$$, $$SYS-06$$]::text[], false, 'active'),
($$PACF-S03-O1$$, 'pacf-item-bank-1.1.0', $$S03$$, $$S$$, 2, $$objective$$, $${"stem":"与固定 Workflow 相比，Agent 的关键差别是什么？","options":[{"id":"A","text":"Agent 必须包含多个模型"},{"id":"B","text":"Workflow 不能使用 AI"},{"id":"C","text":"Agent 一定有头像"},{"id":"D","text":"Agent 由模型在目标和权限内动态决定部分步骤与工具"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":0},{"id":"C","score":0},{"id":"D","score":3}]}$$::jsonb, $$Agent 的核心是动态编排和自主性，而非外观或数量。$$, array[$$S17$$, $$S18$$]::text[], true, 'active'),
($$PACF-S03-S1$$, 'pacf-item-bank-1.1.0', $$S03$$, $$S$$, 4, $$scenario$$, $${"stem":"任务规则稳定、分支已知、错误代价高。应优先选择？","options":[{"id":"A","text":"让模型每次重新规划"},{"id":"B","text":"固定 Workflow，并只在必要节点使用模型判断和人工审批"},{"id":"C","text":"多 Agent 自由协商"},{"id":"D","text":"完全自主 Agent"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":2},{"id":"B","score":3},{"id":"C","score":0},{"id":"D","score":1}]}$$::jsonb, $$稳定高风险流程通常应限制自主性。$$, array[$$S18$$, $$S20$$]::text[], true, 'active'),
($$PACF-S03-C1$$, 'pacf-item-bank-1.1.0', $$S03$$, $$S$$, 4, $$constructed$$, $${"stem":"为一个确实需要 Agent 的用例说明：为什么 Workflow 不够、Agent 目标、工具、记忆、权限、停止条件和人工接管。","rubric":[{"id":"S03-1","description":"动态决策需求真实","maxPoints":1},{"id":"S03-2","description":"工具/记忆与任务匹配","maxPoints":1},{"id":"S03-3","description":"权限和停止条件明确","maxPoints":1},{"id":"S03-4","description":"人工接管与责任明确","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"S03-1","description":"动态决策需求真实","maxPoints":1},{"id":"S03-2","description":"工具/记忆与任务匹配","maxPoints":1},{"id":"S03-3","description":"权限和停止条件明确","maxPoints":1},{"id":"S03-4","description":"人工接管与责任明确","maxPoints":1}]}$$::jsonb, $$避免为了 Agent 而 Agent。$$, array[$$S17$$, $$S18$$, $$S19$$]::text[], false, 'active'),
($$PACF-S03-P1$$, 'pacf-item-bank-1.1.0', $$S03$$, $$S$$, 4, $$practical$$, $${"stem":"构建一个最小 Agent，在沙箱内完成多步任务，并与固定 Workflow 比较成功率、成本和失控行为。","rubric":[{"id":"S03-1","description":"Agent 循环和工具调用可观察","maxPoints":1},{"id":"S03-2","description":"权限限制有效","maxPoints":1},{"id":"S03-3","description":"与 Workflow 使用同一评测集","maxPoints":1},{"id":"S03-4","description":"结论说明是否值得保留 Agent","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"S03-1","description":"Agent 循环和工具调用可观察","maxPoints":1},{"id":"S03-2","description":"权限限制有效","maxPoints":1},{"id":"S03-3","description":"与 Workflow 使用同一评测集","maxPoints":1},{"id":"S03-4","description":"结论说明是否值得保留 Agent","maxPoints":1}]}$$::jsonb, $$Agent 能力包括选择不用 Agent。$$, array[$$SYS-04$$, $$S18$$]::text[], false, 'active'),
($$PACF-S04-O1$$, 'pacf-item-bank-1.1.0', $$S04$$, $$S$$, 3, $$objective$$, $${"stem":"一次 Demo 成功为什么不能证明 AI 系统可靠？","options":[{"id":"A","text":"只要换更贵模型就可靠"},{"id":"B","text":"Demo 时间太短"},{"id":"C","text":"系统可能在不同输入、模型版本和异常条件下失败，需要代表性评测与运行监控"},{"id":"D","text":"必须录制更多视频"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":0},{"id":"C","score":3},{"id":"D","score":0}]}$$::jsonb, $$可靠性需要分布覆盖、回归和运行证据。$$, array[$$S05$$, $$S06$$]::text[], true, 'active'),
($$PACF-S04-S1$$, 'pacf-item-bank-1.1.0', $$S04$$, $$S$$, 4, $$scenario$$, $${"stem":"更换模型后平均质量相近，但高风险案例错误翻倍。应怎么发布？","options":[{"id":"A","text":"阻止发布，分析分层指标并修复后运行回归"},{"id":"B","text":"平均分没变，直接发布"},{"id":"C","text":"只在夜间发布"},{"id":"D","text":"隐藏高风险样本"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":3},{"id":"B","score":0},{"id":"C","score":1},{"id":"D","score":2}]}$$::jsonb, $$总体平均不能掩盖关键风险退化。$$, array[$$SYS-05$$, $$S05$$]::text[], true, 'active'),
($$PACF-S04-C1$$, 'pacf-item-bank-1.1.0', $$S04$$, $$S$$, 4, $$constructed$$, $${"stem":"为一个客服 Agent 设计离线评测集和在线监控，覆盖质量、安全、成本、延迟和人工接管。","rubric":[{"id":"S04-1","description":"样本覆盖常见/边界/高风险","maxPoints":1},{"id":"S04-2","description":"质量和安全阈值明确","maxPoints":1},{"id":"S04-3","description":"在线指标含成本延迟和接管","maxPoints":1},{"id":"S04-4","description":"定义回归和停止发布规则","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"S04-1","description":"样本覆盖常见/边界/高风险","maxPoints":1},{"id":"S04-2","description":"质量和安全阈值明确","maxPoints":1},{"id":"S04-3","description":"在线指标含成本延迟和接管","maxPoints":1},{"id":"S04-4","description":"定义回归和停止发布规则","maxPoints":1}]}$$::jsonb, $$完整评测包含上线前和运行中。$$, array[$$SYS-05$$, $$S06$$]::text[], false, 'active'),
($$PACF-S04-P1$$, 'pacf-item-bank-1.1.0', $$S04$$, $$S$$, 4, $$practical$$, $${"stem":"为一个真实 Workflow/Agent 建立至少 20 个样本的 Eval 包，运行基线与一次改动后的回归并提交日志。","rubric":[{"id":"S04-1","description":"样本具有代表性和风险分层","maxPoints":1},{"id":"S04-2","description":"评分规则可复现","maxPoints":1},{"id":"S04-3","description":"基线与改动结果可比较","maxPoints":1},{"id":"S04-4","description":"日志能定位失败并支持发布决定","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"S04-1","description":"样本具有代表性和风险分层","maxPoints":1},{"id":"S04-2","description":"评分规则可复现","maxPoints":1},{"id":"S04-3","description":"基线与改动结果可比较","maxPoints":1},{"id":"S04-4","description":"日志能定位失败并支持发布决定","maxPoints":1}]}$$::jsonb, $$这是专业全测的系统综合实作候选。$$, array[$$SYS-05$$, $$S05$$, $$S06$$]::text[], false, 'active'),
($$PACF-S05-O1$$, 'pacf-item-bank-1.1.0', $$S05$$, $$S$$, 3, $$objective$$, $${"stem":"组织部署 AI 工具后使用率仍很低，最不充分的解释是什么？","options":[{"id":"A","text":"员工不够积极"},{"id":"B","text":"可能存在权限、技能、流程、支持或激励问题，需要诊断"},{"id":"C","text":"工具未嵌入真实工作"},{"id":"D","text":"风险边界不清导致员工不敢用"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":3},{"id":"B","score":0},{"id":"C","score":0},{"id":"D","score":0}]}$$::jsonb, $$把采用问题归咎个人会忽略系统条件。$$, array[$$S07$$, $$ORG-03$$]::text[], true, 'active'),
($$PACF-S05-S1$$, 'pacf-item-bank-1.1.0', $$S05$$, $$S$$, 5, $$scenario$$, $${"stem":"组织有 20 个 AI 用例提案，但资源只能支持 5 个。最佳做法是？","options":[{"id":"A","text":"全部小规模启动"},{"id":"B","text":"优先领导最喜欢的"},{"id":"C","text":"优先技术最复杂的"},{"id":"D","text":"按价值、风险、准备度、可扩展性和学习价值排序，并设置停止条件"}]}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":1},{"id":"C","score":2},{"id":"D","score":3}]}$$::jsonb, $$组织能力包含组合管理和主动淘汰。$$, array[$$ORG-01$$, $$S05$$]::text[], true, 'active'),
($$PACF-S05-C1$$, 'pacf-item-bank-1.1.0', $$S05$$, $$S$$, 5, $$constructed$$, $${"stem":"设计一个组织 AI 采用方案，包含角色、分层培训、允许/禁止场景、支持渠道、指标和复盘。","rubric":[{"id":"S05-1","description":"角色与责任明确","maxPoints":1},{"id":"S05-2","description":"培训按能力和风险分层","maxPoints":1},{"id":"S05-3","description":"政策与支持可执行","maxPoints":1},{"id":"S05-4","description":"采用/价值/风险指标及复盘完整","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"S05-1","description":"角色与责任明确","maxPoints":1},{"id":"S05-2","description":"培训按能力和风险分层","maxPoints":1},{"id":"S05-3","description":"政策与支持可执行","maxPoints":1},{"id":"S05-4","description":"采用/价值/风险指标及复盘完整","maxPoints":1}]}$$::jsonb, $$工具上线不是组织改变的终点。$$, array[$$S07$$, $$ORG-02$$, $$ORG-03$$]::text[], false, 'active'),
($$PACF-S05-P1$$, 'pacf-item-bank-1.1.0', $$S05$$, $$S$$, 5, $$practical$$, $${"stem":"提交一个真实团队的 30/60/90 天 AI 改变案例，包含基线、用例组合、治理、培训、采用和结果证据。","rubric":[{"id":"S05-1","description":"有真实基线和责任人","maxPoints":1},{"id":"S05-2","description":"治理与能力建设同步","maxPoints":1},{"id":"S05-3","description":"采用和业务结果有数据","maxPoints":1},{"id":"S05-4","description":"能停止无效用例并持续改进","maxPoints":1}]}$$::jsonb, $${"rubric":[{"id":"S05-1","description":"有真实基线和责任人","maxPoints":1},{"id":"S05-2","description":"治理与能力建设同步","maxPoints":1},{"id":"S05-3","description":"采用和业务结果有数据","maxPoints":1},{"id":"S05-4","description":"能停止无效用例并持续改进","maxPoints":1}]}$$::jsonb, $$L5 必须由真实组织采用证据支持。$$, array[$$ORG-01$$, $$ORG-05$$, $$S07$$]::text[], false, 'active')
on conflict (id) do update
set
  item_bank_version = excluded.item_bank_version,
  competency_id = excluded.competency_id,
  dimension_code = excluded.dimension_code,
  target_level = excluded.target_level,
  item_type = excluded.item_type,
  prompt_payload = excluded.prompt_payload,
  scoring_payload = excluded.scoring_payload,
  rationale = excluded.rationale,
  source_anchors = excluded.source_anchors,
  quick_eligible = excluded.quick_eligible,
  status = excluded.status,
  updated_at = now();

insert into public.ai_style_items (
  id, item_bank_version, axis_code, item_type, prompt_payload, scoring_payload, status
)
values
($$ES01$$, 'ai-style-item-bank-1.1.0', 'ES', 'likert', $${"statement":"当新的 AI 模型或功能出现时，我通常想先亲自试用，再决定是否纳入日常方法。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"first","scored":true}$$::jsonb, 'active'),
($$ES02$$, 'ai-style-item-bank-1.1.0', 'ES', 'likert', $${"statement":"与其不断尝试新工具，我更愿意深入掌握少数几种已经验证过的工具。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"second","scored":true}$$::jsonb, 'active'),
($$ES03$$, 'ai-style-item-bank-1.1.0', 'ES', 'likert', $${"statement":"即使当前 AI 方法已经能用，我也会尝试其他方案，看看是否存在更好的可能。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"first","scored":true}$$::jsonb, 'active'),
($$ES04$$, 'ai-style-item-bank-1.1.0', 'ES', 'likert', $${"statement":"选择 AI 工具时，一致性和可重复性通常比新鲜感更重要。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"second","scored":true}$$::jsonb, 'active'),
($$ES05$$, 'ai-style-item-bank-1.1.0', 'ES', 'likert', $${"statement":"我喜欢用同一个真实任务比较多个模型、工具或方法。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"first","scored":true}$$::jsonb, 'active'),
($$ES06$$, 'ai-style-item-bank-1.1.0', 'ES', 'likert', $${"statement":"找到可靠的 AI 流程后，我更愿意持续优化它，而不是经常换一套。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"second","scored":true}$$::jsonb, 'active'),
($$ES07$$, 'ai-style-item-bank-1.1.0', 'ES', 'likert', $${"statement":"我愿意固定留出时间，专门探索还没有明确用途的 AI 新能力。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"first","scored":true}$$::jsonb, 'active'),
($$ES08$$, 'ai-style-item-bank-1.1.0', 'ES', 'likert', $${"statement":"只有看到新方法在真实任务中明显更好，我才会调整现有工具组合。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"second","scored":true}$$::jsonb, 'active'),
($$ES09$$, 'ai-style-item-bank-1.1.0', 'ES', 'likert', $${"statement":"测试 AI 能力边界本身就会让我感到有趣，即使实验未必立刻有结果。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"first","scored":true}$$::jsonb, 'active'),
($$ES10$$, 'ai-style-item-bank-1.1.0', 'ES', 'likert', $${"statement":"一次 AI 实践成功后，我会优先把它整理成稳定方法，再探索下一种玩法。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"second","scored":true}$$::jsonb, 'active'),
($$ES11$$, 'ai-style-item-bank-1.1.0', 'ES', 'likert', $${"statement":"一个新 AI 功能即使价值还不确定，我也愿意先做一个低成本小实验。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"first","scored":true}$$::jsonb, 'active'),
($$ES12$$, 'ai-style-item-bank-1.1.0', 'ES', 'likert', $${"statement":"只要现有 AI 工具仍稳定满足需求，我通常不会因为潮流而更换它。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"second","scored":true}$$::jsonb, 'active'),
($$ES13$$, 'ai-style-item-bank-1.1.0', 'ES', 'likert', $${"statement":"面对陌生 AI 任务时，我更自然地同时试几条路线，再决定深入哪一条。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"first","scored":true}$$::jsonb, 'active'),
($$ES14$$, 'ai-style-item-bank-1.1.0', 'ES', 'likert', $${"statement":"我更喜欢沿着一套清晰的方法长期积累，而不是频繁横向切换。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"second","scored":true}$$::jsonb, 'active'),
($$CO01$$, 'ai-style-item-bank-1.1.0', 'CO', 'likert', $${"statement":"当 AI 帮我做出以前不存在的新东西时，我最有投入感。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"first","scored":true}$$::jsonb, 'active'),
($$CO02$$, 'ai-style-item-bank-1.1.0', 'CO', 'likert', $${"statement":"对我来说，AI 最重要的价值是让已有工作更快、更省力或更可靠。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"second","scored":true}$$::jsonb, 'active'),
($$CO03$$, 'ai-style-item-bank-1.1.0', 'CO', 'likert', $${"statement":"我经常想用 AI 原型化新的内容、产品、服务或体验。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"first","scored":true}$$::jsonb, 'active'),
($$CO04$$, 'ai-style-item-bank-1.1.0', 'CO', 'likert', $${"statement":"相比生成全新的东西，我更容易被减少重复工作和流程浪费的项目吸引。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"second","scored":true}$$::jsonb, 'active'),
($$CO05$$, 'ai-style-item-bank-1.1.0', 'CO', 'likert', $${"statement":"如果只能选一个 AI 项目，我通常会选创造一种新体验，而不是优化已有流程。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"first","scored":true}$$::jsonb, 'active'),
($$CO06$$, 'ai-style-item-bank-1.1.0', 'CO', 'likert', $${"statement":"我主要根据 AI 给现有工作带来的可衡量改善来判断它是否有价值。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"second","scored":true}$$::jsonb, 'active'),
($$CO07$$, 'ai-style-item-bank-1.1.0', 'CO', 'likert', $${"statement":"面对一张白纸构思 AI 可以创造什么，通常比修补现有流程更吸引我。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"first","scored":true}$$::jsonb, 'active'),
($$CO08$$, 'ai-style-item-bank-1.1.0', 'CO', 'likert', $${"statement":"减少错误、等待和交接成本，会比做出一个新概念更让我有成就感。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"second","scored":true}$$::jsonb, 'active'),
($$CO09$$, 'ai-style-item-bank-1.1.0', 'CO', 'likert', $${"statement":"我使用 AI 时，常常先问它还能打开哪些新的表达或产品可能。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"first","scored":true}$$::jsonb, 'active'),
($$CO10$$, 'ai-style-item-bank-1.1.0', 'CO', 'likert', $${"statement":"看到一项工作时，我往往先寻找其中可以标准化、压缩或自动完成的部分。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"second","scored":true}$$::jsonb, 'active'),
($$CO11$$, 'ai-style-item-bank-1.1.0', 'CO', 'likert', $${"statement":"一个可以展示、发布或继续发展的新作品，是我判断 AI 项目成功的重要信号。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"first","scored":true}$$::jsonb, 'active'),
($$CO12$$, 'ai-style-item-bank-1.1.0', 'CO', 'likert', $${"statement":"时间、质量、成本或稳定性的改善，是我判断 AI 项目成功的重要信号。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"second","scored":true}$$::jsonb, 'active'),
($$CO13$$, 'ai-style-item-bank-1.1.0', 'CO', 'likert', $${"statement":"我更喜欢让 AI 扩展想法空间，而不是只把原有做法执行得更快。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"first","scored":true}$$::jsonb, 'active'),
($$CO14$$, 'ai-style-item-bank-1.1.0', 'CO', 'likert', $${"statement":"我更喜欢让 AI 把已有产出变得稳定可复制，而不是持续追求不同的新形式。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"second","scored":true}$$::jsonb, 'active'),
($$RA01$$, 'ai-style-item-bank-1.1.0', 'RA', 'likert', $${"statement":"在依赖一种新的 AI 能力前，我希望大致理解它为什么有效、又可能怎样失败。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"first","scored":true}$$::jsonb, 'active'),
($$RA02$$, 'ai-style-item-bank-1.1.0', 'RA', 'likert', $${"statement":"我更喜欢先用真实任务学习 AI 工具，具体原理可以在需要时再补。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"second","scored":true}$$::jsonb, 'active'),
($$RA03$$, 'ai-style-item-bank-1.1.0', 'RA', 'likert', $${"statement":"AI 给出意外结果时，我通常会先研究原因，再继续调整。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"first","scored":true}$$::jsonb, 'active'),
($$RA04$$, 'ai-style-item-bank-1.1.0', 'RA', 'likert', $${"statement":"相比长时间阅读说明，我更愿意先跑几次快速实验，从结果中学习。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"second","scored":true}$$::jsonb, 'active'),
($$RA05$$, 'ai-style-item-bank-1.1.0', 'RA', 'likert', $${"statement":"即使任务已经成功，我也喜欢弄清楚这套方法为什么奏效。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"first","scored":true}$$::jsonb, 'active'),
($$RA06$$, 'ai-style-item-bank-1.1.0', 'RA', 'likert', $${"statement":"面对不熟悉的 AI 任务，我的第一反应通常是先动手试一次，再根据输出迭代。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"second","scored":true}$$::jsonb, 'active'),
($$RA07$$, 'ai-style-item-bank-1.1.0', 'RA', 'likert', $${"statement":"采用一种 AI 方法前，我更愿意先理解它依赖的假设和适用边界。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"first","scored":true}$$::jsonb, 'active'),
($$RA08$$, 'ai-style-item-bank-1.1.0', 'RA', 'likert', $${"statement":"我通常先做出一个能运行的版本，再逐步建立对背后方法的理解。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"second","scored":true}$$::jsonb, 'active'),
($$RA09$$, 'ai-style-item-bank-1.1.0', 'RA', 'likert', $${"statement":"比较两种 AI 方案时，我会关注它们为何产生不同结果。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"first","scored":true}$$::jsonb, 'active'),
($$RA10$$, 'ai-style-item-bank-1.1.0', 'RA', 'likert', $${"statement":"比较两种 AI 方案时，我更关心哪一种能让我更快推进当前任务。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"second","scored":true}$$::jsonb, 'active'),
($$RA11$$, 'ai-style-item-bank-1.1.0', 'RA', 'likert', $${"statement":"AI 方法失效时，我倾向先形成一个原因假设，再有针对性地验证。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"first","scored":true}$$::jsonb, 'active'),
($$RA12$$, 'ai-style-item-bank-1.1.0', 'RA', 'likert', $${"statement":"AI 方法失效时，我倾向快速改变输入或步骤，直到找到可用路径。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"second","scored":true}$$::jsonb, 'active'),
($$RA13$$, 'ai-style-item-bank-1.1.0', 'RA', 'likert', $${"statement":"理解机制和失败模式，会明显增加我使用 AI 时的踏实感。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"first","scored":true}$$::jsonb, 'active'),
($$RA14$$, 'ai-style-item-bank-1.1.0', 'RA', 'likert', $${"statement":"连续几次亲自尝试带来的反馈，通常比完整的原理说明更能帮助我学习。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"second","scored":true}$$::jsonb, 'active'),
($$PD01$$, 'ai-style-item-bank-1.1.0', 'PD', 'likert', $${"statement":"处理重要任务时，我偏好设置多个检查点，随时查看并修正 AI 的工作。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"first","scored":true}$$::jsonb, 'active'),
($$PD02$$, 'ai-style-item-bank-1.1.0', 'PD', 'likert', $${"statement":"目标和边界明确后，我更希望 AI 连续完成多个步骤，再回来让我检查。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"second","scored":true}$$::jsonb, 'active'),
($$PD03$$, 'ai-style-item-bank-1.1.0', 'PD', 'likert', $${"statement":"我享受通过多轮来回讨论，与 AI 一起逐步完善成果。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"first","scored":true}$$::jsonb, 'active'),
($$PD04$$, 'ai-style-item-bank-1.1.0', 'PD', 'likert', $${"statement":"相比每次逐步协作，我更愿意配置一个可复用的 Agent 或自动流程来执行任务。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"second","scored":true}$$::jsonb, 'active'),
($$PD05$$, 'ai-style-item-bank-1.1.0', 'PD', 'likert', $${"statement":"即使任务容易撤销，我通常也愿意保持参与，而不是让 AI 独立行动。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"first","scored":true}$$::jsonb, 'active'),
($$PD06$$, 'ai-style-item-bank-1.1.0', 'PD', 'likert', $${"statement":"对于低风险、可撤销的任务，我愿意让 AI 在预设范围内自主采取行动。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"second","scored":true}$$::jsonb, 'active'),
($$PD07$$, 'ai-style-item-bank-1.1.0', 'PD', 'likert', $${"statement":"我更喜欢和 AI 一起查看中间产物，边做边共同决定下一步。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"first","scored":true}$$::jsonb, 'active'),
($$PD08$$, 'ai-style-item-bank-1.1.0', 'PD', 'likert', $${"statement":"规则成熟后，我更喜欢只看最终结果、日志和异常，而不是每一步都参与。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"second","scored":true}$$::jsonb, 'active'),
($$PD09$$, 'ai-style-item-bank-1.1.0', 'PD', 'likert', $${"statement":"我更自然地把 AI 当作共同思考和共同创作的搭档。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"first","scored":true}$$::jsonb, 'active'),
($$PD10$$, 'ai-style-item-bank-1.1.0', 'PD', 'likert', $${"statement":"我更自然地把 AI 当作可以接收目标并调度工具的执行系统。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"second","scored":true}$$::jsonb, 'active'),
($$PD11$$, 'ai-style-item-bank-1.1.0', 'PD', 'likert', $${"statement":"任务进行中，我习惯频繁补充判断和反馈，以保持方向一致。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"first","scored":true}$$::jsonb, 'active'),
($$PD12$$, 'ai-style-item-bank-1.1.0', 'PD', 'likert', $${"statement":"只要权限和停止条件清楚，我更愿意定期检查，而不是持续指导。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"second","scored":true}$$::jsonb, 'active'),
($$PD13$$, 'ai-style-item-bank-1.1.0', 'PD', 'likert', $${"statement":"我希望关键表达和决策始终由人参与形成，而不是只在最后批准。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"first","scored":true}$$::jsonb, 'active'),
($$PD14$$, 'ai-style-item-bank-1.1.0', 'PD', 'likert', $${"statement":"我愿意把可规则化的中间决策交给 AI，只保留例外和高影响决策。","scale":{"min":1,"max":7}}$$::jsonb, $${"pole":"second","scored":true}$$::jsonb, 'active'),
($$FX01$$, 'ai-style-item-bank-1.1.0', 'ES', 'forced_choice', $${"prompt":"你有两小时改进自己的 AI 工作方式，更愿意怎样使用？","options":[{"id":"first","text":"测试三种不熟悉的方法，寻找新的可能"},{"id":"second","text":"深入优化目前已经在用的流程"}]}$$::jsonb, $${"scored":false}$$::jsonb, 'active'),
($$FX02$$, 'ai-style-item-bank-1.1.0', 'CO', 'forced_choice', $${"prompt":"你获得一个能力很强的新 AI 系统，最想先做哪个项目？","options":[{"id":"first","text":"创造一个过去很难完成的新作品或体验"},{"id":"second","text":"消除一项昂贵或重复的现有流程"}]}$$::jsonb, $${"scored":false}$$::jsonb, 'active'),
($$FX03$$, 'ai-style-item-bank-1.1.0', 'RA', 'forced_choice', $${"prompt":"一个新 AI 功能给出了意外优秀的结果，你更想先做什么？","options":[{"id":"first","text":"调查它为什么有效以及可能在哪些情况下失败"},{"id":"second","text":"马上把它用于几个真实任务并观察表现"}]}$$::jsonb, $${"scored":false}$$::jsonb, 'active'),
($$FX04$$, 'ai-style-item-bank-1.1.0', 'PD', 'forced_choice', $${"prompt":"一个 Agent 可以安全执行每周一次、容易撤销的任务，你更偏好？","options":[{"id":"first","text":"设置若干中间检查点，与它共同推进"},{"id":"second","text":"设好规则，让它完成后再统一查看"}]}$$::jsonb, $${"scored":false}$$::jsonb, 'active')
on conflict (id) do update
set
  item_bank_version = excluded.item_bank_version,
  axis_code = excluded.axis_code,
  item_type = excluded.item_type,
  prompt_payload = excluded.prompt_payload,
  scoring_payload = excluded.scoring_payload,
  status = excluded.status,
  updated_at = now();

drop trigger if exists update_ai_assessment_sessions_updated_at on public.ai_assessment_sessions;
create trigger update_ai_assessment_sessions_updated_at
  before update on public.ai_assessment_sessions
  for each row execute function public.update_updated_at_column();

drop trigger if exists update_ai_style_items_updated_at on public.ai_style_items;
create trigger update_ai_style_items_updated_at
  before update on public.ai_style_items
  for each row execute function public.update_updated_at_column();

alter table public.ai_assessment_sessions enable row level security;
alter table public.ai_style_items enable row level security;

revoke all on table public.ai_assessment_sessions, public.ai_style_items
  from anon, authenticated;
grant select, insert, update, delete on table public.ai_assessment_sessions, public.ai_style_items
  to service_role;

comment on table public.ai_assessment_sessions is
  'Server-only immutable delivery snapshot for balanced random assessment forms. Browser receives only sanitized prompts.';
comment on table public.ai_style_items is
  'Server-only AI usage-style bank. scoring_payload contains direction and must never be returned to the browser.';
