-- First AI Capability Exam 2026 pilot: mixed-format bank and active instrument.
-- Historical attempts, results, payment orders, memberships, display IDs and QR routes are preserved.

alter table public.ai_assessment_items
  drop constraint if exists ai_assessment_items_item_type_check;

alter table public.ai_assessment_items
  add constraint ai_assessment_items_item_type_check
  check (item_type in ('objective', 'scenario', 'constructed', 'practical', 'choice', 'fill', 'numeric', 'code', 'open'));

insert into public.ai_assessment_instruments (
  id, framework_version, item_bank_version, scoring_version,
  instrument_type, title, description, item_count, status, config, published_at
)
values (
  $$first-ai-capability-exam-2026-v1$$,
  $$pacf-1.0.0$$,
  $$first-ai-exam-bank-1.0.0$$,
  $$first-ai-exam-scoring-1.0.0$$,
  'quick',
  $$第一届 AI 能力摸底考试（2026 试行卷）$$,
  $$从 54 道服务端候选题中分层抽取 30 道计分题与 2 道不计分主观题，覆盖六项 AI 能力与五种题型。$$,
  32,
  'active',
  $${"pool_size":54,"delivered_items":32,"scored_items":30,"unscored_open_items":2,"sampling":{"dimensions":["M","F","T","V","C","S"],"per_dimension":{"basic_choice":2,"scenario_choice":1,"fill_or_numeric":1,"technical":1}},"sections":["basic","scenario","fill","technical","open"],"evidence_grade":"screening"}$$::jsonb,
  now()
)
on conflict (id) do update
set framework_version = excluded.framework_version,
    item_bank_version = excluded.item_bank_version,
    scoring_version = excluded.scoring_version,
    title = excluded.title,
    description = excluded.description,
    item_count = excluded.item_count,
    status = excluded.status,
    config = excluded.config,
    published_at = coalesce(public.ai_assessment_instruments.published_at, excluded.published_at),
    retired_at = null,
    updated_at = now();

update public.ai_assessment_instruments
set status = 'retired', retired_at = coalesce(retired_at, now()), updated_at = now()
where instrument_type in ('quick', 'full', 'applied_lab')
  and id <> $$first-ai-capability-exam-2026-v1$$
  and status <> 'retired';

insert into public.ai_assessment_items (
  id, item_bank_version, competency_id, dimension_code, target_level,
  item_type, prompt_payload, scoring_payload, rationale, source_anchors,
  quick_eligible, status
)
values
($$AIX-M01-B1$$, $$first-ai-exam-bank-1.0.0$$, $$M01$$, $$M$$, 1, $$choice$$, $${"section":"basic","kind":"choice","prompt":"下面哪项最准确地区分“大语言模型”和“聊天产品”？","options":[{"id":"A","text":"模型负责生成，产品还组合界面、账户和工具"},{"id":"B","text":"模型保存账户，产品只负责展示生成的文字"},{"id":"C","text":"模型就是产品，二者只是不同公司的命名习惯"},{"id":"D","text":"模型负责联网，产品负责保存全部训练数据"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":3},{"id":"B","score":0},{"id":"C","score":0},{"id":"D","score":0}],"unscored":false}$$::jsonb, $$产品是模型及外围能力的组合。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-M02-B1$$, $$first-ai-exam-bank-1.0.0$$, $$M02$$, $$M$$, 2, $$choice$$, $${"section":"basic","kind":"choice","prompt":"为什么同一提示词前后可能得到不同答案？","options":[{"id":"A","text":"产品会随机删除部分用户输入以节省服务器成本"},{"id":"B","text":"模型按概率生成，输入上下文和采样也会影响输出"},{"id":"C","text":"模型每次回答后都会立即重新训练自己的参数"},{"id":"D","text":"只要网络速度发生变化，模型知识也会同步变化"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":3},{"id":"C","score":0},{"id":"D","score":0}],"unscored":false}$$::jsonb, $$概率生成与上下文会造成输出波动。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-M03-B1$$, $$first-ai-exam-bank-1.0.0$$, $$M03$$, $$M$$, 2, $$choice$$, $${"section":"basic","kind":"choice","prompt":"关于上下文与长期记忆，哪项说法更准确？","options":[{"id":"A","text":"上传过的文件都会自动进入模型永久训练数据"},{"id":"B","text":"长期记忆只在当前消息生成期间临时起作用"},{"id":"C","text":"上下文服务当前任务，长期记忆需要另行保存和取用"},{"id":"D","text":"上下文和长期记忆都等同于模型原始训练知识"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":0},{"id":"C","score":3},{"id":"D","score":0}],"unscored":false}$$::jsonb, $$上下文、记忆和训练知识必须区分。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-M04-S1$$, $$first-ai-exam-bank-1.0.0$$, $$M04$$, $$M$$, 3, $$choice$$, $${"section":"scenario","kind":"choice","prompt":"每月只处理20份固定格式表格，有人建议立刻搭多 Agent。你会先做什么？","options":[{"id":"A","text":"比较模板、脚本、单次模型和 Agent 的成本与错误率"},{"id":"B","text":"先搭多 Agent 原型，再根据展示效果决定是否保留"},{"id":"C","text":"先购买能力最强的模型，再讨论具体流程如何调整"},{"id":"D","text":"先让多个模型互相投票，再把多数答案作为最终结果"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":3},{"id":"B","score":2},{"id":"C","score":0},{"id":"D","score":1}],"unscored":false}$$::jsonb, $$高水平选型从最小可靠方案和实测开始。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-M05-S1$$, $$first-ai-exam-bank-1.0.0$$, $$M05$$, $$M$$, 2, $$choice$$, $${"section":"scenario","kind":"choice","prompt":"AI 给出的建议造成业务损失，下面哪种责任理解更合适？","options":[{"id":"A","text":"供应商应承担责任，因为模型生成了原始建议"},{"id":"B","text":"发布者仍负有责任，因为采用和执行决定由人作出"},{"id":"C","text":"用户无需负责，因为页面已经标注内容由 AI 生成"},{"id":"D","text":"责任取决于价格，付费模型应自动承担更多责任"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":1},{"id":"B","score":3},{"id":"C","score":0},{"id":"D","score":0}],"unscored":false}$$::jsonb, $$AI 不会接管采用者的最终责任。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-M03-F1$$, $$first-ai-exam-bank-1.0.0$$, $$M03$$, $$M$$, 1, $$fill$$, $${"section":"fill","kind":"fill","prompt":"当前任务中模型可直接使用的提示、历史消息和文件内容，通常统称为______。","placeholder":"请输入答案","unscored":false}$$::jsonb, $${"accepted_answers":["上下文","context","当前上下文"],"unscored":false}$$::jsonb, $$检查最基础的上下文概念。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-M01-F1$$, $$first-ai-exam-bank-1.0.0$$, $$M01$$, $$M$$, 2, $$fill$$, $${"section":"fill","kind":"fill","prompt":"由模型根据目标动态选择步骤并调用工具的系统，通常称为______。","placeholder":"请输入答案","unscored":false}$$::jsonb, $${"accepted_answers":["agent","智能体","ai agent","ai智能体"],"unscored":false}$$::jsonb, $$区分 Agent 与普通聊天或固定流程。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-M05-T1$$, $$first-ai-exam-bank-1.0.0$$, $$M05$$, $$M$$, 3, $$code$$, $${"section":"technical","kind":"code","prompt":"阅读下面的工具权限配置，最需要优先调整什么？","code":"tools:\n  email.read: all_mailboxes\n  payment.create: false\nlogging:\n  retention_days: 30","options":[{"id":"A","text":"把日志保留时间从30天调整为更短的7天"},{"id":"B","text":"把读取邮件权限改成只读取指定业务文件夹"},{"id":"C","text":"把模型名称从通用名称改为具体版本编号"},{"id":"D","text":"把执行结果的文字长度限制为一千字以内"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":1},{"id":"B","score":3},{"id":"C","score":2},{"id":"D","score":0}],"unscored":false}$$::jsonb, $$最小权限优先于界面与输出细节。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-M01-O1$$, $$first-ai-exam-bank-1.0.0$$, $$M01$$, $$M$$, 3, $$open$$, $${"section":"open","kind":"open","prompt":"请向完全不懂技术的人解释：模型、Workflow 和 Agent 有什么不同，并各举一个例子。","placeholder":"请用 50–200 字作答","unscored":true}$$::jsonb, $${"unscored":true}$$::jsonb, $$观察概念能否被迁移和解释。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-F01-B1$$, $$first-ai-exam-bank-1.0.0$$, $$F01$$, $$F$$, 1, $$choice$$, $${"section":"basic","kind":"choice","prompt":"哪个请求最清楚地定义了预期结果？","options":[{"id":"A","text":"请认真帮我处理这份材料，尽量写得专业一些"},{"id":"B","text":"请扮演资深顾问，对材料进行全面深入的分析"},{"id":"C","text":"请根据附件，为新用户写一页可独立完成注册的说明"},{"id":"D","text":"请先自由发挥完成初稿，之后我再告诉你是否合适"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":1},{"id":"C","score":3},{"id":"D","score":0}],"unscored":false}$$::jsonb, $$结果定义需要受众、产物和成功条件。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-F02-B1$$, $$first-ai-exam-bank-1.0.0$$, $$F02$$, $$F$$, 2, $$choice$$, $${"section":"basic","kind":"choice","prompt":"复杂任务拆解时，哪项原则最有帮助？","options":[{"id":"A","text":"按照每一步文字数量相同的方式平均拆分任务"},{"id":"B","text":"按照可验证中间产物和前后依赖关系拆分任务"},{"id":"C","text":"按照可用模型数量拆分，让每个模型负责一个部分"},{"id":"D","text":"按照操作人员数量拆分，避免同一个人重复检查"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":3},{"id":"C","score":1},{"id":"D","score":2}],"unscored":false}$$::jsonb, $$拆解应围绕依赖与可验证产物。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-F05-B1$$, $$first-ai-exam-bank-1.0.0$$, $$F05$$, $$F$$, 2, $$choice$$, $${"section":"basic","kind":"choice","prompt":"下面哪项最接近可执行的验收标准？","options":[{"id":"A","text":"整体读起来足够高级，能给负责人留下深刻印象"},{"id":"B","text":"结构完整、语言顺畅，并尽量覆盖更多相关信息"},{"id":"C","text":"一页内覆盖问题、证据和下一步，数字均可追溯"},{"id":"D","text":"使用统一模板和品牌颜色，避免出现明显排版问题"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":1},{"id":"C","score":3},{"id":"D","score":2}],"unscored":false}$$::jsonb, $$验收标准应可明确判定且包含关键质量条件。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-F03-S1$$, $$first-ai-exam-bank-1.0.0$$, $$F03$$, $$F$$, 2, $$choice$$, $${"section":"scenario","kind":"choice","prompt":"AI 写出的品牌文案很通用，下一轮最值得补充什么？","options":[{"id":"A","text":"真实受众、品牌主张、素材、禁用表达和正反例"},{"id":"B","text":"更多角色称号、情绪词语、感叹号和流行表达"},{"id":"C","text":"更高随机性、更长输出长度和更多候选文案数量"},{"id":"D","text":"更多同行文章、热门标题和未经筛选的历史聊天"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":3},{"id":"B","score":0},{"id":"C","score":1},{"id":"D","score":2}],"unscored":false}$$::jsonb, $$真实材料和边界比角色咒语更有效。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-F04-S1$$, $$first-ai-exam-bank-1.0.0$$, $$F04$$, $$F$$, 3, $$choice$$, $${"section":"scenario","kind":"choice","prompt":"长对话已经多次偏离目标，最稳妥的处理方式是什么？","options":[{"id":"A","text":"继续在原对话补充要求，保留模型已经生成的全部内容"},{"id":"B","text":"让模型自己回顾错误，再直接生成最终版本并立即提交"},{"id":"C","text":"整理目标、状态和未决问题，在新会话中用摘要重新开始"},{"id":"D","text":"把历史对话完整复制给另一个模型，让它判断谁更可靠"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":1},{"id":"B","score":2},{"id":"C","score":3},{"id":"D","score":0}],"unscored":false}$$::jsonb, $$状态摘要和重启比无限追加更可靠。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-F05-F1$$, $$first-ai-exam-bank-1.0.0$$, $$F05$$, $$F$$, 1, $$fill$$, $${"section":"fill","kind":"fill","prompt":"在生成前约定准确性、格式、受众和通过条件，这组要求叫作______。","placeholder":"请输入答案","unscored":false}$$::jsonb, $${"accepted_answers":["验收标准","验收条件","acceptance criteria","通过标准"],"unscored":false}$$::jsonb, $$检查验收概念。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-F02-F1$$, $$first-ai-exam-bank-1.0.0$$, $$F02$$, $$F$$, 1, $$fill$$, $${"section":"fill","kind":"fill","prompt":"把复杂任务分成可执行、可检查的中间步骤，叫作任务______。","placeholder":"请输入答案","unscored":false}$$::jsonb, $${"accepted_answers":["拆解","分解","task decomposition"],"unscored":false}$$::jsonb, $$检查任务拆解概念。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-F03-T1$$, $$first-ai-exam-bank-1.0.0$$, $$F03$$, $$F$$, 2, $$code$$, $${"section":"technical","kind":"code","prompt":"下面的任务配置最明显缺少哪项信息？","code":"{\n  \"task\": \"write onboarding guide\",\n  \"source\": \"product-notes.md\",\n  \"format\": \"one page\"\n}","options":[{"id":"A","text":"目标读者以及他们完成阅读后应能做什么"},{"id":"B","text":"模型回答时允许使用的最大字符数量限制"},{"id":"C","text":"调用接口时使用同步还是异步请求方式"},{"id":"D","text":"最终文档存放在云端还是本地硬盘目录"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":3},{"id":"B","score":1},{"id":"C","score":0},{"id":"D","score":2}],"unscored":false}$$::jsonb, $$受众与结果是任务契约核心。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-F01-O1$$, $$first-ai-exam-bank-1.0.0$$, $$F01$$, $$F$$, 3, $$open$$, $${"section":"open","kind":"open","prompt":"同事只写了“请帮我做好市场调研”。请把它改写成可执行任务，至少包含目标、材料、范围和验收标准。","placeholder":"请用 50–200 字作答","unscored":true}$$::jsonb, $${"unscored":true}$$::jsonb, $$观察任务契约表达能力。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-T01-B1$$, $$first-ai-exam-bank-1.0.0$$, $$T01$$, $$T$$, 1, $$choice$$, $${"section":"basic","kind":"choice","prompt":"环境变量最常见的用途是什么？","options":[{"id":"A","text":"把服务端密钥与公开代码分开保存并在运行时读取"},{"id":"B","text":"把网页样式与业务逻辑分开保存并在构建时合并"},{"id":"C","text":"把用户上传文件自动转成模型能够训练的数据格式"},{"id":"D","text":"把每次模型回答永久同步到所有访问设备的缓存"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":3},{"id":"B","score":1},{"id":"C","score":0},{"id":"D","score":0}],"unscored":false}$$::jsonb, $$环境变量常用于运行配置与敏感值隔离。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-T03-B1$$, $$first-ai-exam-bank-1.0.0$$, $$T03$$, $$T$$, 1, $$choice$$, $${"section":"basic","kind":"choice","prompt":"AI 回答里带有引用链接，下一步最合理的做法是什么？","options":[{"id":"A","text":"先检查链接能否打开，再核对原文是否支持对应主张"},{"id":"B","text":"先让另一个模型评价链接，再决定是否打开原始页面"},{"id":"C","text":"先把引用格式改成统一样式，再检查作者姓名是否完整"},{"id":"D","text":"先统计引用数量是否足够，再决定这份回答能否采用"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":3},{"id":"B","score":1},{"id":"C","score":2},{"id":"D","score":0}],"unscored":false}$$::jsonb, $$引用存在不等于引用已被核验。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-T04-B1$$, $$first-ai-exam-bank-1.0.0$$, $$T04$$, $$T$$, 2, $$choice$$, $${"section":"basic","kind":"choice","prompt":"处理访谈、图片和表格时，怎样组织工作区更可靠？","options":[{"id":"A","text":"按文件大小排序上传，让模型自行识别每份材料的作用"},{"id":"B","text":"建立清单、命名和版本规则，再按材料类型分批处理"},{"id":"C","text":"把所有材料压缩为一个文件，减少上传和下载操作次数"},{"id":"D","text":"先把图片转成截图，把表格转成文字后统一放进对话"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":1},{"id":"B","score":3},{"id":"C","score":0},{"id":"D","score":2}],"unscored":false}$$::jsonb, $$结构化工作区降低遗漏和版本混乱。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-T02-S1$$, $$first-ai-exam-bank-1.0.0$$, $$T02$$, $$T$$, 2, $$choice$$, $${"section":"scenario","kind":"choice","prompt":"需要处理含隐私的内部会议记录，选工具时先确认什么？","options":[{"id":"A","text":"组织许可、数据处理方式、访问权限和删除机制"},{"id":"B","text":"模型排行榜、生成速度、上下文长度和界面体验"},{"id":"C","text":"同事使用人数、社区热度、模板数量和插件丰富度"},{"id":"D","text":"免费额度、折扣活动、分享功能和移动端适配情况"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":3},{"id":"B","score":2},{"id":"C","score":1},{"id":"D","score":0}],"unscored":false}$$::jsonb, $$敏感任务应先通过合规与权限门槛。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-T05-S1$$, $$first-ai-exam-bank-1.0.0$$, $$T05$$, $$T$$, 3, $$choice$$, $${"section":"scenario","kind":"choice","prompt":"教程要求使用 API Key，最安全的处理方式是什么？","options":[{"id":"A","text":"写入前端配置文件，并通过缩短变量名称降低泄露风险"},{"id":"B","text":"存入服务端密钥管理，限制权限并设置轮换与撤销方式"},{"id":"C","text":"发送到团队群聊，确保需要接手的人都能随时复制使用"},{"id":"D","text":"写入公开示例代码，只保留密钥前后几位作为识别标记"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":1},{"id":"B","score":3},{"id":"C","score":0},{"id":"D","score":2}],"unscored":false}$$::jsonb, $$密钥需要服务端保存、最小权限和生命周期管理。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-T05-F1$$, $$first-ai-exam-bank-1.0.0$$, $$T05$$, $$T$$, 2, $$numeric$$, $${"section":"fill","kind":"numeric","prompt":"某模型输入价格为每100万Token 20元。一次任务平均使用25,000 Token，运行60次，输入成本约为多少元？","placeholder":"请输入数字","unscored":false}$$::jsonb, $${"numeric_answer":30,"numeric_tolerance":0.01,"unscored":false}$$::jsonb, $$1.5M Token × 20元/M = 30元。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-T02-F1$$, $$first-ai-exam-bank-1.0.0$$, $$T02$$, $$T$$, 2, $$numeric$$, $${"section":"fill","kind":"numeric","prompt":"某工具月费99元，每月预计节省6小时。若人工时间按每小时30元计算，每月净节省约多少元？","placeholder":"请输入数字","unscored":false}$$::jsonb, $${"numeric_answer":81,"numeric_tolerance":0.01,"unscored":false}$$::jsonb, $$节省180元减去99元月费，净节省81元。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-T05-T1$$, $$first-ai-exam-bank-1.0.0$$, $$T05$$, $$T$$, 2, $$code$$, $${"section":"technical","kind":"code","prompt":"下面哪一行最可能造成密钥泄露？","code":"1  const key = Deno.env.get(\"MODEL_API_KEY\");\n2  const result = await callModel(key, prompt);\n3  console.log(\"key:\", key);\n4  return { ok: result.ok };","options":[{"id":"A","text":"第1行：从运行环境读取密钥，不把值写入源代码"},{"id":"B","text":"第2行：在服务端请求中使用读取到的密钥"},{"id":"C","text":"第3行：把完整密钥写入浏览器控制台日志"},{"id":"D","text":"第4行：仅向调用者返回接口是否成功的状态"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":1},{"id":"C","score":3},{"id":"D","score":0}],"unscored":false}$$::jsonb, $$浏览器日志会把服务端秘密暴露给前端使用者。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-T01-O1$$, $$first-ai-exam-bank-1.0.0$$, $$T01$$, $$T$$, 2, $$open$$, $${"section":"open","kind":"open","prompt":"请用小白能理解的语言解释文件路径、文件格式和 API Key，并各举一个常见错误。","placeholder":"请用 50–200 字作答","unscored":true}$$::jsonb, $${"unscored":true}$$::jsonb, $$观察数字基础能否被准确解释。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-V01-B1$$, $$first-ai-exam-bank-1.0.0$$, $$V01$$, $$V$$, 1, $$choice$$, $${"section":"basic","kind":"choice","prompt":"核验 AI 给出的统计数字时，最重要的动作是什么？","options":[{"id":"A","text":"比较多个模型是否给出相同数值和相似的解释过程"},{"id":"B","text":"回到原始来源核对口径、时期、样本和计算方法"},{"id":"C","text":"检查数字是否保留小数以及图表是否符合视觉规范"},{"id":"D","text":"要求模型提高置信度并使用更肯定的表达重新回答"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":1},{"id":"B","score":3},{"id":"C","score":2},{"id":"D","score":0}],"unscored":false}$$::jsonb, $$核验必须回到可检查的原始证据。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-V03-B1$$, $$first-ai-exam-bank-1.0.0$$, $$V03$$, $$V$$, 1, $$choice$$, $${"section":"basic","kind":"choice","prompt":"上传内部材料给 AI 前，最先应该判断什么？","options":[{"id":"A","text":"材料是否足够完整，避免模型因为缺少背景产生误解"},{"id":"B","text":"材料是否涉及隐私、保密、版权以及组织使用许可"},{"id":"C","text":"材料是否适合转换成PDF，以保持不同设备排版一致"},{"id":"D","text":"材料是否已经有人使用过，避免重复支付模型调用费用"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":1},{"id":"B","score":3},{"id":"C","score":0},{"id":"D","score":2}],"unscored":false}$$::jsonb, $$先判断数据和授权边界。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-V04-B1$$, $$first-ai-exam-bank-1.0.0$$, $$V04$$, $$V$$, 2, $$choice$$, $${"section":"basic","kind":"choice","prompt":"决定任务需要多强人工监督，主要看哪些因素？","options":[{"id":"A","text":"模型价格、生成速度、界面复杂度和团队使用人数"},{"id":"B","text":"提示长度、回答字数、文件数量和网络连接速度"},{"id":"C","text":"影响大小、错误可逆性、数据敏感性和可检测性"},{"id":"D","text":"用户职位、工具品牌、订阅档位和模型参数规模"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":0},{"id":"B","score":1},{"id":"C","score":3},{"id":"D","score":0}],"unscored":false}$$::jsonb, $$监督强度应该匹配风险。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-V01-S1$$, $$first-ai-exam-bank-1.0.0$$, $$V01$$, $$V$$, 2, $$choice$$, $${"section":"scenario","kind":"choice","prompt":"AI 给出一篇论文和 DOI，但 DOI 无法解析。你会怎样处理？","options":[{"id":"A","text":"删除 DOI 后保留论文结论，并在文末标注来源待确认"},{"id":"B","text":"让模型生成一个新的 DOI，再比较两个编号哪个更合理"},{"id":"C","text":"核对作者、题名和数据库记录，找不到就视为未证实"},{"id":"D","text":"寻找题目相似的论文，用相似论文替换原来的引用信息"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":1},{"id":"B","score":0},{"id":"C","score":3},{"id":"D","score":2}],"unscored":false}$$::jsonb, $$不存在的来源不能通过格式修补变成证据。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-V05-S1$$, $$first-ai-exam-bank-1.0.0$$, $$V05$$, $$V$$, 4, $$choice$$, $${"section":"scenario","kind":"choice","prompt":"Agent 可以读取邮件并发起付款，怎样降低恶意邮件诱导付款的风险？","options":[{"id":"A","text":"限制单笔付款金额，让 Agent 自行判断邮件是否可信"},{"id":"B","text":"只处理纯文本邮件，通过第二个模型后自动完成付款"},{"id":"C","text":"隔离邮件中的指令，限制权限并要求付款前人工确认"},{"id":"D","text":"降低模型温度并记录日志，异常时再由管理员追查"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":1},{"id":"B","score":2},{"id":"C","score":3},{"id":"D","score":1}],"unscored":false}$$::jsonb, $$不可信输入、最小权限和人工批准需要组合使用。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-V04-F1$$, $$first-ai-exam-bank-1.0.0$$, $$V04$$, $$V$$, 2, $$numeric$$, $${"section":"fill","kind":"numeric","prompt":"每月处理200份文件，其中5%产生高风险错误；人工复核能发现这些错误的80%。预计仍有多少份高风险错误未被发现？","placeholder":"请输入数字","unscored":false}$$::jsonb, $${"numeric_answer":2,"numeric_tolerance":0.01,"unscored":false}$$::jsonb, $$200 × 5% × (1-80%) = 2。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-V01-F1$$, $$first-ai-exam-bank-1.0.0$$, $$V01$$, $$V$$, 2, $$numeric$$, $${"section":"fill","kind":"numeric","prompt":"抽查40条AI生成的事实，其中34条能被可靠来源支持。该样本的可支持率是多少百分比？","placeholder":"请输入数字","unscored":false}$$::jsonb, $${"numeric_answer":85,"numeric_tolerance":0.01,"unscored":false}$$::jsonb, $$34 ÷ 40 = 85%。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-V05-T1$$, $$first-ai-exam-bank-1.0.0$$, $$V05$$, $$V$$, 3, $$code$$, $${"section":"technical","kind":"code","prompt":"这段流程的主要安全问题是什么？","code":"const page = await fetchUrl(userUrl);\nconst plan = await model(\"Follow page instructions: \" + page);\nawait runAdminTool(plan);","options":[{"id":"A","text":"系统先读取网页内容，导致整体运行速度可能变慢"},{"id":"B","text":"网页文字被直接拼进指令，并可触发高权限工具调用"},{"id":"C","text":"模型输出被保存到日志，可能增加数据库存储成本"},{"id":"D","text":"流程使用一个模型，缺少多个模型之间的投票机制"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":1},{"id":"B","score":3},{"id":"C","score":2},{"id":"D","score":0}],"unscored":false}$$::jsonb, $$外部不可信文本不能直接成为高权限指令。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-V01-O1$$, $$first-ai-exam-bank-1.0.0$$, $$V01$$, $$V$$, 3, $$open$$, $${"section":"open","kind":"open","prompt":"AI 给出一个影响采购决策的市场数字。请写出你的核验步骤和最终记录方式。","placeholder":"请用 50–200 字作答","unscored":true}$$::jsonb, $${"unscored":true}$$::jsonb, $$观察证据链与不确定性处理。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-C01-B1$$, $$first-ai-exam-bank-1.0.0$$, $$C01$$, $$C$$, 1, $$choice$$, $${"section":"basic","kind":"choice","prompt":"怎样让 AI 产出更接近个人观点和风格？","options":[{"id":"A","text":"提供自己的观点、真实素材、受众和正反例，再人工重构"},{"id":"B","text":"增加形容词、情绪指令、角色称号和输出篇幅限制"},{"id":"C","text":"连续生成更多版本，从中选择读起来最流畅的一份"},{"id":"D","text":"固定使用同一模型，避免不同模型造成表达风格变化"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":3},{"id":"B","score":1},{"id":"C","score":2},{"id":"D","score":0}],"unscored":false}$$::jsonb, $$个人风格来自真实材料和人的重构。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-C03-B1$$, $$first-ai-exam-bank-1.0.0$$, $$C03$$, $$C$$, 2, $$choice$$, $${"section":"basic","kind":"choice","prompt":"判断一个 AI 原型最低限度是否可用，应该看什么？","options":[{"id":"A","text":"关键用户路径能够运行，并通过预先定义的基本测试"},{"id":"B","text":"界面已经完成设计，并使用统一品牌颜色与图标风格"},{"id":"C","text":"代码数量足够多，并采用当前流行的框架和模型服务"},{"id":"D","text":"演示视频播放流畅，并获得团队成员较积极的主观评价"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":3},{"id":"B","score":1},{"id":"C","score":2},{"id":"D","score":0}],"unscored":false}$$::jsonb, $$可用原型需要真实路径与测试。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-C05-B1$$, $$first-ai-exam-bank-1.0.0$$, $$C05$$, $$C$$, 2, $$choice$$, $${"section":"basic","kind":"choice","prompt":"评估 AI 是否真正提效，应该比较哪些指标？","options":[{"id":"A","text":"生成速度、使用次数、提示长度和用户主观新鲜感"},{"id":"B","text":"质量、端到端耗时、返工、成本和相关风险变化"},{"id":"C","text":"模型参数、上下文长度、排行榜和社区讨论热度"},{"id":"D","text":"页面访问、按钮点击、账号数量和内容生成总字数"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":1},{"id":"B","score":3},{"id":"C","score":0},{"id":"D","score":2}],"unscored":false}$$::jsonb, $$价值衡量需要端到端质量、成本和风险。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-C02-S1$$, $$first-ai-exam-bank-1.0.0$$, $$C02$$, $$C$$, 2, $$choice$$, $${"section":"scenario","kind":"choice","prompt":"AI 写出一份流畅摘要，但你无法解释关键概念。应该怎么做？","options":[{"id":"A","text":"保留摘要并补充术语表，让读者自行判断关键概念含义"},{"id":"B","text":"让模型把文字改得更简单，再直接提交给目标读者使用"},{"id":"C","text":"回到原文与领域知识，确认理解后重写并标注不确定性"},{"id":"D","text":"换另一个模型重新摘要，选择两份结果中表达更完整的一份"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":1},{"id":"B","score":0},{"id":"C","score":3},{"id":"D","score":2}],"unscored":false}$$::jsonb, $$领域交付不能以不理解的流畅文字代替。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-C04-S1$$, $$first-ai-exam-bank-1.0.0$$, $$C04$$, $$C$$, 3, $$choice$$, $${"section":"scenario","kind":"choice","prompt":"一段提示词每次都需要大量手工修改，怎样把它沉淀成资产？","options":[{"id":"A","text":"把所有历史修改合并成长提示词，并要求模型自行选择内容"},{"id":"B","text":"拆分变量、输入、样例、验收和异常说明，再做复用测试"},{"id":"C","text":"固定第一次成功结果，以后只替换少量名词和数字字段"},{"id":"D","text":"交给多个模型分别改写，选择平均字数最接近的一套版本"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":1},{"id":"B","score":3},{"id":"C","score":2},{"id":"D","score":0}],"unscored":false}$$::jsonb, $$复用资产需要结构化变量与测试。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-C05-F1$$, $$first-ai-exam-bank-1.0.0$$, $$C05$$, $$C$$, 2, $$numeric$$, $${"section":"fill","kind":"numeric","prompt":"原流程每次耗时50分钟，使用AI后生成15分钟、人工检查20分钟、返工5分钟。每次净节省多少分钟？","placeholder":"请输入数字","unscored":false}$$::jsonb, $${"numeric_answer":10,"numeric_tolerance":0.01,"unscored":false}$$::jsonb, $$50-(15+20+5)=10分钟。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-C05-F2$$, $$first-ai-exam-bank-1.0.0$$, $$C05$$, $$C$$, 2, $$numeric$$, $${"section":"fill","kind":"numeric","prompt":"AI流程处理100项任务，第一次通过验收82项，返工后又通过12项。最终通过率是多少百分比？","placeholder":"请输入数字","unscored":false}$$::jsonb, $${"numeric_answer":94,"numeric_tolerance":0.01,"unscored":false}$$::jsonb, $$(82+12)÷100=94%。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-C03-T1$$, $$first-ai-exam-bank-1.0.0$$, $$C03$$, $$C$$, 2, $$code$$, $${"section":"technical","kind":"code","prompt":"这段代码为什么不能证明原型已经可用？","code":"async function buildPrototype(prompt) {\n  const screenshot = await model.generateImage(prompt);\n  return screenshot;\n}","options":[{"id":"A","text":"它只生成界面截图，没有验证关键用户路径能否完成"},{"id":"B","text":"它使用异步函数，因此无法保证图片一定能正确显示"},{"id":"C","text":"它没有指定字体和颜色，因此不能达到品牌交付标准"},{"id":"D","text":"它只调用一次模型，因此无法比较多个模型之间差异"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":3},{"id":"B","score":1},{"id":"C","score":2},{"id":"D","score":0}],"unscored":false}$$::jsonb, $$产出截图不等于真实功能路径可运行。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-C05-O1$$, $$first-ai-exam-bank-1.0.0$$, $$C05$$, $$C$$, 3, $$open$$, $${"section":"open","kind":"open","prompt":"选择一个你常做的任务，写出使用AI前后的质量、耗时、返工和风险比较方法。","placeholder":"请用 50–200 字作答","unscored":true}$$::jsonb, $${"unscored":true}$$::jsonb, $$观察价值是否能被测量而非凭感觉判断。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-S01-B1$$, $$first-ai-exam-bank-1.0.0$$, $$S01$$, $$S$$, 1, $$choice$$, $${"section":"basic","kind":"choice","prompt":"哪类流程通常更适合优先尝试 AI 改造？","options":[{"id":"A","text":"高频耗时、输入输出较清楚，并且错误影响可以控制"},{"id":"B","text":"受到关注、展示效果明显，但业务价值暂时无法测量"},{"id":"C","text":"规则很少、后果严重，并且发生错误后难以人工恢复"},{"id":"D","text":"只出现一次、范围不明，需要很多部门同时改变的任务"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":3},{"id":"B","score":1},{"id":"C","score":0},{"id":"D","score":2}],"unscored":false}$$::jsonb, $$优先选择有价值且可控制的流程。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-S02-B1$$, $$first-ai-exam-bank-1.0.0$$, $$S02$$, $$S$$, 2, $$choice$$, $${"section":"basic","kind":"choice","prompt":"可靠 Workflow 除了正常步骤，还必须定义什么？","options":[{"id":"A","text":"异常、重试、状态、人工交接和重复执行处理"},{"id":"B","text":"角色语气、界面颜色、输出字数和模型人格名称"},{"id":"C","text":"团队口号、项目代号、演示脚本和宣传发布计划"},{"id":"D","text":"更多模型、更长提示、更大上下文和更高随机参数"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":3},{"id":"B","score":0},{"id":"C","score":1},{"id":"D","score":2}],"unscored":false}$$::jsonb, $$可靠流程必须处理失败与交接。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-S04-B1$$, $$first-ai-exam-bank-1.0.0$$, $$S04$$, $$S$$, 3, $$choice$$, $${"section":"basic","kind":"choice","prompt":"一次 Demo 成功为什么不能证明系统可靠？","options":[{"id":"A","text":"演示环境通常网速更快，因此无法代表普通用户设备表现"},{"id":"B","text":"系统可能在不同输入、版本和异常条件下出现新的失败"},{"id":"C","text":"演示人员更熟悉操作，因此普通用户需要接受更多培训"},{"id":"D","text":"一次运行缺少宣传素材，因此无法证明产品具有市场价值"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":1},{"id":"B","score":3},{"id":"C","score":2},{"id":"D","score":0}],"unscored":false}$$::jsonb, $$可靠性需要代表性测试和持续观测。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-S03-S1$$, $$first-ai-exam-bank-1.0.0$$, $$S03$$, $$S$$, 3, $$choice$$, $${"section":"scenario","kind":"choice","prompt":"任务规则稳定、分支已知且错误代价高，应优先选择什么？","options":[{"id":"A","text":"固定 Workflow，在必要节点加入模型判断和人工审批"},{"id":"B","text":"自主 Agent，让模型根据每次输入自由重新规划步骤"},{"id":"C","text":"多 Agent 协商，通过多数投票决定每一步如何执行"},{"id":"D","text":"单次聊天，把全部材料提交后要求模型一次完成任务"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":3},{"id":"B","score":2},{"id":"C","score":1},{"id":"D","score":0}],"unscored":false}$$::jsonb, $$稳定高风险任务更适合受控工作流。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-S05-S1$$, $$first-ai-exam-bank-1.0.0$$, $$S05$$, $$S$$, 4, $$choice$$, $${"section":"scenario","kind":"choice","prompt":"团队有20个AI用例提案但只能支持5个，应怎样选择？","options":[{"id":"A","text":"按提交时间排序，优先支持最早提出并已准备演示的项目"},{"id":"B","text":"按价值、风险、准备度和学习价值排序，并设停止条件"},{"id":"C","text":"按技术复杂度排序，优先建设最能展示模型能力的项目"},{"id":"D","text":"按部门规模排序，优先满足使用人数最多部门的全部需求"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":1},{"id":"B","score":3},{"id":"C","score":0},{"id":"D","score":2}],"unscored":false}$$::jsonb, $$组织采用需要组合管理和停止机制。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-S02-F1$$, $$first-ai-exam-bank-1.0.0$$, $$S02$$, $$S$$, 2, $$fill$$, $${"section":"fill","kind":"fill","prompt":"支付回调可能重复到达。让相同请求重复执行仍只产生一次权益，这种设计叫作______。","placeholder":"请输入答案","unscored":false}$$::jsonb, $${"accepted_answers":["幂等","幂等性","idempotency","idempotent"],"unscored":false}$$::jsonb, $$检查工作流幂等概念。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-S02-F2$$, $$first-ai-exam-bank-1.0.0$$, $$S02$$, $$S$$, 2, $$fill$$, $${"section":"fill","kind":"fill","prompt":"系统失败时回到安全、可人工处理状态的设计，通常称为______或降级。","placeholder":"请输入答案","unscored":false}$$::jsonb, $${"accepted_answers":["回退","fallback","故障回退","安全回退"],"unscored":false}$$::jsonb, $$检查失败恢复概念。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-S02-T1$$, $$first-ai-exam-bank-1.0.0$$, $$S02$$, $$S$$, 3, $$code$$, $${"section":"technical","kind":"code","prompt":"这段订单处理流程最明显缺少什么？","code":"async function onPaid(order) {\n  await grantMembership(order.userId);\n  await sendWelcomeMessage(order.userId);\n}","options":[{"id":"A","text":"支付成功页面的动画、颜色和完成提示文案"},{"id":"B","text":"订单唯一性与幂等检查，避免重复发放会员权益"},{"id":"C","text":"更多支付渠道之间的价格比较和自动推荐逻辑"},{"id":"D","text":"第二个模型对用户身份和支付意愿的独立判断"}],"unscored":false}$$::jsonb, $${"option_scores":[{"id":"A","score":1},{"id":"B","score":3},{"id":"C","score":0},{"id":"D","score":2}],"unscored":false}$$::jsonb, $$外部回调必须按唯一订单幂等处理。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active'),
($$AIX-S02-O1$$, $$first-ai-exam-bank-1.0.0$$, $$S02$$, $$S$$, 4, $$open$$, $${"section":"open","kind":"open","prompt":"请为“每周收集三个渠道的客户反馈并生成产品待办”设计流程，说明输入、步骤、人工检查、异常处理和效果指标。","placeholder":"请用 50–200 字作答","unscored":true}$$::jsonb, $${"unscored":true}$$::jsonb, $$综合观察流程和可靠性设计。$$, array['first-ai-exam-2026-pilot']::text[], true, 'active')
on conflict (id) do update
set item_bank_version = excluded.item_bank_version,
    competency_id = excluded.competency_id,
    dimension_code = excluded.dimension_code,
    target_level = excluded.target_level,
    item_type = excluded.item_type,
    prompt_payload = excluded.prompt_payload,
    scoring_payload = excluded.scoring_payload,
    rationale = excluded.rationale,
    source_anchors = excluded.source_anchors,
    quick_eligible = excluded.quick_eligible,
    status = excluded.status,
    updated_at = now();

comment on constraint ai_assessment_items_item_type_check on public.ai_assessment_items is
  'Supports legacy PACF rows plus the mixed-format First AI Exam item bank.';
